### ISSUE TITLE
Multi-select limited by bounding box

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#111]
When using CTRL+drag to select multiple nodes, the crosshair is only visible in the top-section of the 2D network view. The highlighted box is the area where drag selection is possible. 
![fullexample](https://user-images.githubusercontent.com/1420108/52451840-96bcc180-2b0e-11e9-809d-fdad2370ec63.PNG)

I've tracked it down to this div. By setting the height to a larger value, I regain some crosshair control but ultimately the underlying code is dynamic so simply setting it is ineffective overall. 
![image](https://user-images.githubusercontent.com/1420108/52451874-c79cf680-2b0e-11e9-82fa-f43818acd5bb.png)

**Comment by AABoyles** [comment]
Resolved by 77f3d404ca92001b69cecab29956ae183cb00c31
