### ISSUE TITLE
Alignment taking a long time

### ISSUE THREAD

**Issue by rlechtenberg** [CDCgov/MicrobeTrace#12]
I'm finding that it takes an inordinate amount of time to align evern just 12 sequences in WebMicrobeTrace, and that this appears to be true regardless of my alignment options (e.g., aligner/algorithm, local vs global, number of cores, etc.). The application hasn't gotten past the below for about 30 minutes now! The same set of sequences align in a split second in the desktop application, but I'd like to be able to use the web application if possible as my understanding is that that's what's being actively maintained and developed. Any help? Thanks!

![image](https://user-images.githubusercontent.com/38964413/46505791-13e5cc00-c7e7-11e8-867c-6a9ae3b7ae99.png)

**Comment by AABoyles** [comment]
Hmmm, It probably broke in the background. Would you mind doing the following?

1. Load up the sequences using a set of configurations that takes too long to load
2. Once the network is loading and it's hanging on the alignment step, hit F12. This should open your browser's developer tools.
3. Click on the "Console" tab.
4. Take a screenshot of its contents and post it here.

Thanks!

**Comment by rlechtenberg** [comment]
No problem! Thanks for the help! Here you go...

![image](https://user-images.githubusercontent.com/38964413/46544354-3d026d00-c878-11e8-9cb6-6c27da46d5ed.png)

**Comment by AABoyles** [comment]
Yup, that definitely failed! One more request: try the same thing on the [MicrobeTrace Bleeding-Edge Development Version](https://devmicrobetrace.herokuapp.com/). If _that_ hangs, please repeat [those screenshot steps](https://github.com/CDCgov/WebMicrobeTrace/issues/12#issuecomment-427387841). 
Sorry, this should be the last diagnostic test, and hopefully I'll be able to fix your problem

**Comment by rlechtenberg** [comment]
Doesn't hang!

**Comment by ells** [comment]
We've just replicated this with a handful of completely different FASTA files in the production branch (confirmed issue not present in the development branch). Not sure of the cause but definitely a showstopper. For now the 'bleeding edge' version is your best bet until we can pin it down.

Perhaps of note, the alignment preview seems to fail and only show the first sequence.

**Comment by AABoyles** [comment]
The Bleeding-Edge version has succeeded the production release that was throwing that error.
