### ISSUE TITLE
Gantt Chart chops off long ID labels

### ISSUE THREAD

**Issue by AABoyles** [CDCgov/MicrobeTrace#124]
The Gantt Chart's y-axis location is [hard-coded](https://github.com/CDCgov/MicrobeTrace/blob/master/components/gantt.html#L102). It's far enough right that most of most IDs show just fine. However, the left sides of long IDs spill off-screen, which could make interpretation potentially difficult. Let's fix this by setting the y-axis location dynamically, according to the width of the widest ID.

**Comment by jaywokim** [comment]
added code to figure out the width of the longest node id and use that as the left margin attribute
