### ISSUE TITLE
Tree nomenclature?

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#127]
Something to think about-Tree seems a generic term, and the difference between that and the unweighted dendrogram is not clear from the name. Of course you can see the difference visually by trying the two...
any other term we could use?

**Comment by AABoyles** [comment]
Not sure. The tree/dendrogram distinction comes from D3. I started calling the weighted dendrogram a weighted tree, but @nrf1 suggested we call it a weighted dendrogram instead. The distinction really is lost on me. Do you have any suggestions?

**Comment by ikb6** [comment]
Will look around- another item for the meeting- Bill is the expert...

**Comment by jaywokim** [comment]
type has been resolved to [tree, weighted dendrogram, unweighted dendrogram ]
