### ISSUE TITLE
Branch color too light

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#128]
Could you darken the default to black and perhaps increase the weight of the line a bit? Here's an example of a MEGA tree. Font for leaf labels could be Arial  10 or 12.
![image](https://user-images.githubusercontent.com/33426295/54551126-cec3e980-4983-11e9-85eb-ba0fee7a1c6c.png)

**Comment by AABoyles** [comment]
Yes, definitely!
