### ISSUE TITLE
Export Color Legend from Network View

### ISSUE THREAD

**Issue by ridgwayconsulting** [CDCgov/MicrobeTrace#137]
1.  In the attached graph, I'm coloring the nodes using a variable with 18 categories.  The first time I did it, the nodes after the 9th category were all the same color as the 9th (i.e., they were all teal).  The second time I did it, with a different edge list, the legend cycled through the first 9 colors a second time, but categories 10 through 18 were colored the same as "None" (light grey).
2.  When the graph is exported as a .png, the legend isn't exported with it (the attachments are screen captures).

![listeria_v2](https://user-images.githubusercontent.com/46609449/54945797-0810d200-4f0d-11e9-91c8-cc0b420b3200.png)
![legend1](https://user-images.githubusercontent.com/46609449/54946262-14e1f580-4f0e-11e9-8957-44ce1947ff67.png)
![legend2](https://user-images.githubusercontent.com/46609449/54946277-1f9c8a80-4f0e-11e9-8562-9decdd232652.png)

**Comment by AABoyles** [comment]
Hey @cdcArmstrong! Thanks for filing this issue!
1. This definitely sounds like a bug. The node colors should cycle through the list of colors again (like you saw in the second case), but the nodes being colored accordingly. I'll attempt to replicate. Were you using [Prod](https://microbetrace.herokuapp.com), [Dev](https://devmicrobetrace.herokuapp.com) or something else?
2. This is a long-standing technical issue. We're working on a solution, but it won't be ready in the short-term (i.e. within days or weeks). In general, the workaround is precisely what you've done (screen-capping). Sorry, I know this is a bit onerous.

**Comment by cdcArmstrong** [comment]
I was using the production app (microbetrace.herokuapp.com).


I think these were the files I was using.  I don't think there's anything confidential in them, but they're not mine, so please delete them after you've done the testing.


Thanks!

Greg

________________________________

**Comment by jaywokim** [comment]
issue number one seems to be resolved and issue number two seems like an enhancement. 
I will relabel to enhancement.

**Comment by jaywokim** [comment]
need provision for shapes and sizes on the 2d network view
