### ISSUE TITLE
Phylogenetic Tree - Branch length label resets on application of color

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#146]
When coloring nodes by a categorical variable from inside the phylogenetic view, the branch labels will reset on their own.

For example:
1.) Turn off branch length labels
![image](https://user-images.githubusercontent.com/1420108/57044254-fe7b3800-6c37-11e9-8e68-a1a179bc3ccf.png)

2.) Set color nodes by to a variable (note color change in the provided screenshots)
![image](https://user-images.githubusercontent.com/1420108/57044281-181c7f80-6c38-11e9-8b4f-00103d142cd8.png)

At this point, the tree is re-rendered but branch lengths are re-enabled. Viewing the settings widget shows branch lengths as hidden. When I 'kick' (toggle button on to off again) it properly hides the branch labels.

**Comment by AABoyles** [comment]
Can't reproduce, must've fixed at some point.
