### ISSUE TITLE
Wildcard searching

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#157]
Would like the ability to use wildcards (e.g., asterisk symbol "*") as a wildcard. We don't need full regular expressions, just the ability to use multiple wildcards in a string.

**Comment by AABoyles** [comment]
Implemented in b92bb02d8b247c8d23a513718f650b6e4b01d9cb. See [Searching](https://github.com/CDCgov/MicrobeTrace/wiki/Searching) for details.
