### ISSUE TITLE
Drag Selection appears to be broken

### ISSUE THREAD

**Issue by AABoyles** [CDCgov/MicrobeTrace#170]

**Comment by jaywokim** [comment]
2D network 
[CTRL]  +   mouse drag should produce shadow box to select nodes

**Comment by jaywokim** [comment]
issue with D3 behavior update: https://github.com/d3/d3-drag/issues/62
have to bypass default brush filter

**Comment by jaywokim** [comment]
applying explicit filter exposed other problems with brush when using drag selection so reverted back to previous version of 'brush' and 'end' callback functions
