### ISSUE TITLE
File Saving and Re-import 

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#173]
The following refers to development environment....

When I import our 'Demo_outbreak_Sequences.fasta' THEN export the node list as a CSV.

Reusing that node list, while mapping the sequence column, fails as shown:
![image](https://user-images.githubusercontent.com/1420108/66857949-4f68b980-ef56-11e9-8bbc-c549e159f079.png)

It doesn't seem to like the ambiguity column: 
Uncaught TypeError: Cannot set property '_ambiguity' of undefined
    at Worker.computer.onmessage (common.js:814)

That being said, renaming the headers in the CSV does not resolve the issue. 

If I remove all other columns, leaving only "ID" and "Seq" it does work. 

Example:

id | seq
-- | --
30582_KF773572_H96cl05 | AATCTGGCCTTCCAACAAGGGGAGGCCAGGGAATTTCATTCAGAGCAG---------------------------------ACTAGAGCCAACAGCCCCACCAGCAGAGAGCTTCAAGTTCGAGGAGACAACCCC---------------------TGCTCCGAAGCAGGAATCGAAAGACAAGGAGCCACCCTTAACTTCCCTCAAATCACTCTTTGGCAGCGACCCCTTGTCACAATAAAAGTAGGGGGCCAGATAAAGGAAGCTCTCTTAGATACAGGAGCAGATGATACAGTATTAGAAGAATTAAATCTGCCAGGAAAATGGAAACCAAAAATGATAGGAGGAATTGGAGGTTTTATCAAAGTAAGACAATATGATCAAATAGTTATAGAAATTTGTGGGAAAAAAGCTATAGGTTCAGTATTAGTAGGACCTACACCTGTCAACATAATTGGAAGAAATATGTTGACTCAGCTTGGATGTACACTAAATTTTCCAATTAGTCCCATTGAGACTGTACCAGTAAAATTAAAGCCAGGAATGGATGGCCCAAAAGTTAAACAATGGCCATTGACAGAAGAAAAAATAAAAGCATTAACAGCAATTTGTGAAGAAATGGAAAAGGAAGGAAAAATTACAAAAATTGGGCCTGAAAATCCATATAACACTCCAATATTTGCCATAAAAAAGAAGGACAGTACTAAATGGAGGAAATTAGTAGATTTCAGGGAACTCAATAAAAGAACTCAAGACTTTTGGGAAGTTCAATTAGGAATACCACACCCAGCAGGGTTAAAAAAGAAAAAGTCAGTGACAGTGCTGGATGTGGGGGATGCATATTTTTCAGTTCCTTTAGATGAAAGCTTCAGGAAATATACTGCATTCACCATACCTAGTATAAACAATGAAACACCAGGGATTAGATATCAATATAATGTACTTCCACAAGGATGGAAAGGATCACCAGCAATATTCCAGAGTAGCATGACAAAAATCTTAGAGCCCTTTAGGACACAAAACCCAGACATAGTTATCTATCAATATATGGATGACTTGTATGTAGGATCTGACTTAGAAATAGGGCAACATAGAGCAAAAATAGAGGAGTTAAGAGAACATTTATTGAGGTGGGGATTTACCACTCCAGACAAGAAACATCAGAAAGAACCCCCATTTCTGTGGATGGGGTATGAACTCCATCCTGACAAATGGACAGTACAGCCTATAAATCTGCCAGAAAAAGAGAGCTGGACTGTCAATGATATACAGAAGTTAGTGGGAAAATTAAACTGGGCAAGTCAGATTTACCCAGGGATTAAAGTAAGACAACTATGTAAACTCCTTAGAGGAGCCAAAGCACTAACAGACATAGTACCACTGACTGAAGAAGCAGAATTAGAATTGGCAGAGAACAGGGAAATTCTAAAAGAACCAGTACATGGGGTATATTATGACCCATCA-
30582_KF773573_H96cl06 | AATCTGGCCTTCCAACAAGGGGAGGCCAGGGAATTTCATTCAGAGCAG---------------------------------ACTAGAGCCAACAGCCCCACCAGCAGAGAGCTTCAAGTTCGAGGAGACAACCCC---------------------TGCTCCGAAGCAGGAATCGAAAGACAAGGAGCCACCCTTAACTTCCCTCAAATCACTCTTTGGCAGCGACCCCTTGTCACAATAAAAGTAGGGGGCCAGATAAAGGAAGCTCTCTTAGATACAGGAGCAGATGATACAGTATTAGAAGAATTAAATCTGCCAGGAAAATGGAAACCAAAAATGATAGGAGGAATTGGAGGTTTTATCAAAGTAAGACAATATGATCAAATAGTTATAGAAATTTGTGGGAAAAAAGCTATAGGTTCAGTATTAGTAGGACCTACACCTGTCAACATAATTGGAAGAAATATGTTGACTCAGCTTGGATGTACACTAAATTTTCCAATTAGTCCCATTGAGACTGTACCAGTAAAATTAAAGCCAGGAATGGATGGCCCAAAAGTTAAACAATGGCCATTGACAGAAGAAAAAATAAAAGCATTAACAGCAATTTGTGAAGAAATGGAAAAGGAAGGAAAAATTACAAAAATTGGGCCTGAAAATCCATATAACACTCCAATATTTGCCATAAAAAAGAAGGACAGTACTAAATGGAGGAAATTAGTAGATTTCAGGGAACTCAATAAAAGAACTCAAGACTTTTGGGAAGTTCAATTAGGAATACCACACCCAGCAGGGTTAAAAAAGAAAAAGTCAGTGACAGTGCTGGATGTGGGGGATGCATATTTTTCAGTTCCTTTAGATGAAAGCTTCAGGAAATATACTGCATTCACCATACCTAGTATAAACAATGAAACACCAGGGATTAGATATCAATATAATGTACTTCCACAAGGATGGAAAGGATCACCAGCAATATTCCAGAGTAGCATGACAAAAATCTTAGAGCCCTTTAGGACACAAAACCCAGACATAGTTATCTATCAATATATGGATGACTTGTATGTAGGATCTGACTTAGAAATAGGGCAACATAGAGCAAAAATAGAGGAGTTAAGAGAACATTTATTGAGGTGGGGATTTACCACTCCAGACAAGAAACATCAGAAAGAACCCCCATTTCTGTGGATGGGGTATGAGCTCCATCCTGACAAATGGACAGTACAGCCTATAAATCTGCCAGAAAAAGAGAGCTGGACTGTCAATGATATACAGAAGTTAGTGGGAAAATTAAACTGGGCAAGTCAGATTTACCCAGGGATTAAAGTAAGACAACTATGTAAACTCCTTAGAGGAGCCAAAGCACTAACAGACATAGTACCACTGACTGAAGAAGCAGAATTAGAATTGGCAGAGAACAGGGAAATTCTAAAAGAACCAGTACATGGGGTATATTATGACCCATCA-

**Comment by jaywokim** [comment]
I think I isolated the issue
This is a partial dump of the session.data.nodes object below.
The "index":""       is empty but this property is used as index for setting the _ambiguity property. 
I fixed it by injecting a "0" for empty string. But the real solution is figuring out why "0" isn't there in the first place. 

[
{
"index": "",
"_id": "30582_KF773572_H96cl05",
"selected": "",
"cluster": "",
"visible": "true",
"degree": "27",
"origin": "Demo_outbreak_Sequences.fas",
"seq": "AATCTGGCCTTCCAACAAGGGGAGGCCAGGGAATTTCATTCAGAGCAG---------------------------------

**Comment by jaywokim** [comment]
some more of the dump for context:

[
{
"index": "",
"_id": "30582_KF773572_H96cl05",
"selected": "",
"cluster": "",
"visible": "true",
"degree": "27",
"origin": "Demo_outbreak_Sequences.fas",
"seq": "AATCTGGCCTTCCAACAAGGGGAGGCCAGGGAATTTCATTCAGAGCAG---------------------------------ACTAGAGCCAACAGCCCCACCAGCAGAGAGCTTCAAGTTCGAGGAGACAACCCC---------------------TGCTCCGAAGCAGGAATCGAAAGACAAGGAGCCACCCTTAACTTCCCTCAAATCACTCTTTGGCAGCGACCCCTTGTCACAATAAAAGTAGGGGGCCAGATAAAGGAAGCTCTCTTAGATACAGGAGCAGATGATACAGTATTAGAAGAATTAAATCTGCCAGGAAAATGGAAACCAAAAATGATAGGAGGAATTGGAGGTTTTATCAAAGTAAGACAATATGATCAAATAGTTATAGAAATTTGTGGGAAAAAAGCTATAGGTTCAGTATTAGTAGGACCTACACCTGTCAACATAATTGGAAGAAATATGTTGACTCAGCTTGGATGTACACTAAATTTTCCAATTAGTCCCATTGAGACTGTACCAGTAAAATTAAAGCCAGGAATGGATGGCCCAAAAGTTAAACAATGGCCATTGACAGAAGAAAAAATAAAAGCATTAACAGCAATTTGTGAAGAAATGGAAAAGGAAGGAAAAATTACAAAAATTGGGCCTGAAAATCCATATAACACTCCAATATTTGCCATAAAAAAGAAGGACAGTACTAAATGGAGGAAATTAGTAGATTTCAGGGAACTCAATAAAAGAACTCAAGACTTTTGGGAAGTTCAATTAGGAATACCACACCCAGCAGGGTTAAAAAAGAAAAAGTCAGTGACAGTGCTGGATGTGGGGGATGCATATTTTTCAGTTCCTTTAGATGAAAGCTTCAGGAAATATACTGCATTCACCATACCTAGTATAAACAATGAAACACCAGGGATTAGATATCAATATAATGTACTTCCACAAGGATGGAAAGGATCACCAGCAATATTCCAGAGTAGCATGACAAAAATCTTAGAGCCCTTTAGGACACAAAACCCAGACATAGTTATCTATCAATATATGGATGACTTGTATGTAGGATCTGACTTAGAAATAGGGCAACATAGAGCAAAAATAGAGGAGTTAAGAGAACATTTATTGAGGTGGGGATTTACCACTCCAGACAAGAAACATCAGAAAGAACCCCCATTTCTGTGGATGGGGTATGAACTCCATCCTGACAAATGGACAGTACAGCCTATAAATCTGCCAGAAAAAGAGAGCTGGACTGTCAATGATATACAGAAGTTAGTGGGAAAATTAAACTGGGCAAGTCAGATTTACCCAGGGATTAAAGTAAGACAACTATGTAAACTCCTTAGAGGAGCCAAAGCACTAACAGACATAGTACCACTGACTGAAGAAGCAGAATTAGAATTGGCAGAGAACAGGGAAATTCTAAAAGAACCAGTACATGGGGTATATTATGACCCATCA-",
"_seqInt": {},
"_diff": 69,
"_ambiguity": "0.037542663514614105"
},
{
"index": "1",
"_id": "30582_KF773573_H96cl06",
"selected": "",
"cluster": "",
"visible": "true",
"degree": "26",

**Comment by jaywokim** [comment]
I think I found the root of the problem:
files.html   ~line 1005
filterXSS(node[key])
the filter function is removing the "0"
I recommend customizing the filter rules to allow "0" when parsing CSV

**Comment by jaywokim** [comment]
recommended solution:
// safeNode[safeKey] = filterXSS(node[key]);
safeNode[safeKey] =  (typeof node[key] === 'string')  ?   filterXSS(node[key]) : node[key];

**Comment by jaywokim** [comment]
committed code to fix issue
