### ISSUE TITLE
Newick Import

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#174]
The following relates to the development environment...

Upon import of a newick file and pressing launch, the screen locks up and the user is unaware that background processing of the file has begun. 

I have an example with 663 sequences that appeared to hang for ~83s prior to showing the loading/processing modal menu.

![image](https://user-images.githubusercontent.com/1420108/66858607-9efbb500-ef57-11e9-8e8f-31a62c1a8188.png)

Adding an accompanying node list had a negligible impact on load time. 

![image](https://user-images.githubusercontent.com/1420108/66859010-79bb7680-ef58-11e9-8e80-b0ea73e45551.png)

**Comment by jaywokim** [comment]
placed "loading-information-modal"  in promise scheme to load before long running file processing using patristic library.
