### ISSUE TITLE
3D View Broken

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#175]
**The following refers to the development environment...**

When loading from a .fasta file (no other inputs), and opening the 3D view, only a single node is displayed. 

This can be replicated with the Demo_outbreak_Sequences.fas file on the github. 

```
An error is thrown in the console:
Uncaught Error: node not found: 30577_KF773462_C94cl30
    at Nd (bundle.secondary.js:5)
    at d (bundle.secondary.js:5)
    at Function.Id.u.links (bundle.secondary.js:5)
    at Function.update (bundle.secondary.js:8)
    at bundle.secondary.js:5
    at c (bundle.secondary.js:5)

```
Note that the ID in the error is not the same as the one shown on-screen. Rather, the single node shown on-screen is the first sequence in the input file:
![image](https://user-images.githubusercontent.com/1420108/66859460-5ba24600-ef59-11e9-97a2-8c43ed635d4e.png)

Interestingly, this can be averted by generating sequences from the experimental settings menu:
![image](https://user-images.githubusercontent.com/1420108/66859603-9906d380-ef59-11e9-8b7e-62d9fc352585.png)

**Comment by AABoyles** [comment]
Fixed
