### ISSUE TITLE
Interface with other software

### ISSUE THREAD

**Issue by rlechtenberg** [CDCgov/MicrobeTrace#177]
We have a system we've developed for storing and accessing reported HIV genotype sequences and derived information (resistance profiles, cluster info, etc.). I'd like to enable users to easily visualize cluster info for a person or cluster selected therein. To do that, I'd like to leverage WebMicrobeTrace (such a great tool!) if possible, but don't want to burden users with having to learn it and so am wondering if there's any way (that currently exists or that could be developed) to programmatically call WebMicrobeTrace and automatically add files, launch, and specify a view (i.e., Table  2D Network), maybe using paramterized URLs or an API. Thanks a lot for your work on WebMicrobeTrace!

**Comment by AABoyles** [comment]
Hey @rlechtenberg! This is super cool, and something we love to work on! We tried URL-encoded sessions awhile back (see #26). Unfortunately, the data is usually too large to be practicably URL-encoded, even with aggressive compression. That said, we've had some success integrating with other platforms by making small modifications to the MicrobeTrace code and deploying it alongside the other application. See [Assimilating MicrobeTrace](https://github.com/CDCgov/MicrobeTrace/wiki/Assimilating-MicrobeTrace) to see how this is done.

I'd be happy to help you accomplish this latter goal, if you can tell me a little more about the environment you're working in. Feel free to [email me](mailto:nsp3@cdc.gov) to discuss it.
