### ISSUE TITLE
Collapsed Nodes in Map are not saved upon export to PNG

### ISSUE THREAD

**Issue by billswitzer2** [CDCgov/MicrobeTrace#178]
What is saved:
![image](https://user-images.githubusercontent.com/31011205/68234149-a3534500-ffce-11e9-8ad8-60367c5beecf.png)
What is supposed to be saved:
![image](https://user-images.githubusercontent.com/31011205/68234204-b9610580-ffce-11e9-8f09-5e0c0c7b0047.png)

**Comment by AABoyles** [comment]
The node-collapsing library seems to run in an SVG overlay, rather than on the Canvas map, so we can't export it directly. Need to brainstorm this a bit.

**Comment by billswitzer2** [comment]
Thanks Tony!

**Comment by ells** [comment]
Can you default the output to render only the nodes, instead of the collapsed value? I don't think this is solvable without a lot of effort on your part to rebuild collapsing in an SVG-friendly manner.

**Comment by jaywokim** [comment]
https://www.npmjs.com/package/leaflet-image
Leaflet.markercluster: will not work because it uses HTML for clusters.
possible solution: https://orenw.wordpress.com/2015/06/07/export-leaflet-map-to-image/

**Comment by billswitzer2** [comment]
Thanks. Give it a try…
