### ISSUE TITLE
Waterfall in Dev does not display node IDs. Shows them in prod.

### ISSUE THREAD

**Issue by billswitzer2** [CDCgov/MicrobeTrace#179]
![image](https://user-images.githubusercontent.com/31011205/68238939-0f867680-ffd8-11e9-8d5b-98a4994ee4fb.png)

**Comment by billswitzer2** [comment]
Thanks Tony! What was the issue?

**Comment by AABoyles** [comment]
Wwhile back we had a user with an `id` column in her node list that *wasn't* the unique identifier. So we changed the internal node identifier field from `id` to `_id`. But I forgot to update the Waterfall view to be aware of that change.

**Comment by billswitzer2** [comment]
Thx!
