### ISSUE TITLE
Flow diagram reverts to default view after viewing different tab i.e. 2D network

### ISSUE THREAD

**Issue by billswitzer2** [CDCgov/MicrobeTrace#182]
Selected variables to show in flow diagram. Opened a new window view and then when went back to flow diagram and it reverted to the default values (index)

**Comment by jaywokim** [comment]
common.js:1586
 if (["radio", "checkbox"].includes($id[0].type)) {
          if (session.style.widgets[id]) $id.click();

**Comment by jaywokim** [comment]
Right now whenever a new view is launched, the procedure is to click on any  radio and checkbox widget types found in the session on any open view tabs:
if (["radio", "checkbox"].includes($id[0].type)) {
          if (session.style.widgets[id]) $id.click();

The Dataset “buttons” are actually radio type. So when you click on a new view the “Nodes” button/radio is pressed and your variable updates are reset to index and the diagram is redrawn.

**Comment by jaywokim** [comment]
I placed in a type of name space for widget default implementation. 
The code will check if the widget is contained in the newly launched view. If it is not contained in the new view, it will not act on the widget default. If the widget is in the newly launched view then it will act on the default. 
if($(contentItem.element[0]).find($id).length > 0)  // issue #182

**Comment by jaywokim** [comment]
common.js:1588
 if($(contentItem.element[0]).find($id).length > 0)   $id.click();   // issue #182

scope out the widget before apply default settings
