### ISSUE TITLE
Failed Import of Data in DevBranch

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#183]
We are running into an issue that only occurs in the dev branch using the most simplistic input link list. The following will not import: 

source | target | distance
-- | -- | --
1 | 2 | 0
3 | 4 | 0.00000834
5 | 6 | 0.00000834
5 | 3 | 0.00000834
5 | 4 | 0.00000834
5 | 4 | 0.00000834
7 | 8 | 0.004462751
9 | 10 | 0.004462751
9 | 11 | 0.004462751

On load, it shows an interesting count of nodes that is a likely hint to the bug...
![image](https://user-images.githubusercontent.com/1420108/68959845-e2d31b80-079c-11ea-9d85-7852abe870b2.png)

We know there are only 11 total nodes, but this is showing as if each link source and target are unique nodes...totaling out to 18. 

The following error message might also be helpful, because it shows how far into the computation workflow it gets before it errors out. It looks like it is erroring when it tries to construct a tree using the available, but sparse distance data?
![image](https://user-images.githubusercontent.com/1420108/68959958-288fe400-079d-11ea-9c6d-e5f933f4f6a2.png)

**Comment by jaywokim** [comment]
added error handler to worker for uncaught errors on [src/common.js:947](https://github.com/CDCgov/MicrobeTrace/blob/master/src/common.js#L947)

    computer.onerror = (e) => {
      console.log(e);
      resolve(); //issue #183
    };

**Comment by jaywokim** [comment]
bypass error thrown from patristic library for now , could be bug in library or malformed matrix entries.
