### ISSUE TITLE
Sequence viewer is not rendering with FASTA input only

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#186]
The sequence view is failing in the development branch when rendering sequences from a FASTA file. This can be replicated with the [demo file](https://raw.githubusercontent.com/CDCgov/MicrobeTrace/master/demo/Demo_outbreak_Sequences.fas).

The following error is thrown:
![image](https://user-images.githubusercontent.com/1420108/71102811-0ec03300-2187-11ea-9eaa-68875c52e97d.png)

Note that this issue does not persist when rendering a CSV where sequences are embedded in the file. This can be demonstrated by using the 'experimental' menu to spin up random sequences at file-load.

**Comment by jaywokim** [comment]
alignment viewer library is expecting "id" property in the seq object but the supplied object has "_id"
if(s.id.length > offset) offset = s.id.length;
causing "undefined" error

**Comment by jaywokim** [comment]
added "id" property to the nodes array when preparing the argument for the alignment viewer library
