### ISSUE TITLE
Opacity slider on export needs broader setting range.

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#188]
The opacity slider, on advanced settings of an image export, does not completely remove the image when the bar is dragged all the way to the left.

We need the far left to be invisible, the default to be ~20% opacity, and the maximum to be the full image.

**Comment by jaywokim** [comment]
![Capture](https://user-images.githubusercontent.com/55855925/73012368-21600480-3de4-11ea-8ef9-fb72bc7d818f.PNG)
water mark option isn't available on DEV build currently but is available on the production version

**Comment by jaywokim** [comment]
putting the feature back into DEV code base

**Comment by jaywokim** [comment]
2d_network
--aggregation
bubbles
--crosstab
flow_diagram
gantt
heatmap
histogram
phylogenetic_tree
scatterplot
