### ISSUE TITLE
Backwards branches on weighted dendrogram with a .tsv SNP matrix

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#194]
![Salmonella_SNPTree_issue](https://user-images.githubusercontent.com/33426295/74156552-8ab58500-4be4-11ea-8710-efb66b843159.jpg)

From Salmonella group in WA- Krisandra Allen (krisandra.allen@doh.wa.gov)
She used a .tsv file, saw backwards branches. Weighted dendrogram does this, but not unweighted or Tree views. We've seen this with TB in past when Tony was working on phylogeny libraries.
Issue is in both Prod and Dev

Also, When I use her file, I get branch lengths which are not integers, even though I made sure settings reflect SNPs, and not TN93, see below
![Salmonella_SNPTree_issue_ASTree](https://user-images.githubusercontent.com/33426295/74157017-850c6f00-4be5-11ea-8c29-cb95fd60bc91.JPG)

**Comment by jaywokim** [comment]
![Capture](https://user-images.githubusercontent.com/55855925/74262644-44872100-4ccb-11ea-8624-18c17fcec3ea.PNG)
![Capture](https://user-images.githubusercontent.com/55855925/74262789-8a43e980-4ccb-11ea-9d05-6f011621025d.PNG)

length is calculated as negative value
