### ISSUE TITLE
Mapping distances renders link-less network

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#195]
This behavior exists only in the development branch:

When mapping the distances in a simple link list that contains distances equal to zero, the resulting network does not render any of the links. 

|Source|Target|Distance|
|----|----|----|
|14|15|0.0|
|14|19|0.0|
|14|61|0.0|

With the resulting network as follows:
![image](https://user-images.githubusercontent.com/1420108/75076267-b599b600-54cd-11ea-904b-31735567b21b.png)

When viewing the histogram, in the global settings menu, the zeros are apparently rendered:
![image](https://user-images.githubusercontent.com/1420108/75076318-db26bf80-54cd-11ea-806c-68927809449b.png)

However, they are absent in the generalized histogram:
![image](https://user-images.githubusercontent.com/1420108/75076433-2c36b380-54ce-11ea-839d-b7ad9ef86c81.png)

These are shown as "NaN" in the table view:
![image](https://user-images.githubusercontent.com/1420108/75076401-10cba880-54ce-11ea-8c42-06c54c07926c.png)

**Comment by jaywokim** [comment]
filterXSS causing non string elements to be blanked out
