### ISSUE TITLE
Custom tip labels in phylotree viewer

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#199]
Currently, our phylogenetic trees only enable the user to display the tip label. We would like users to be able to select the tip label value from a dropdown list of variables contained in the node list.

This is a direct user-request, so let's prioritize it since we know it should be a light lift.

This feature request may also need some accommodations in TidyTree to function, unsure.

**Comment by jaywokim** [comment]
Implemented enhancement on label and tool tip.

**Comment by jaywokim** [comment]
fixed issue with session nodes reference to id or _id
