### ISSUE TITLE
Enhance Google Analytics

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#200]
**_Research effort needed to determine the feasibility of this enhancement._** 

We would like increased resolution over traffic flow within the application. We are not sure whether this is possible, given our single-view implementation. 

1.) **Behavior Flow diagrams.** These describe user's interactions with various screens and provides drop-off rates at each interaction. Here is an example from a website that I manage:
![image](https://user-images.githubusercontent.com/1420108/76644620-b69e9000-652d-11ea-8ff4-b1d5ff2aeb4b.png)

2.) **Per-view metrics.** These show pageviews as well as time-per-page, but I'd like to collect them per view if possible. Here is another example from the same site:
![image](https://user-images.githubusercontent.com/1420108/76644643-cf0eaa80-652d-11ea-9894-863d15811942.png)

**Comment by jaywokim** [comment]
event triggers:
Nearest neighbor 
2d image export
bacterial sequences (SNPs) vs HIV or other viruses (TN93 distances) [Distance Metric]

**Comment by jaywokim** [comment]
event trigger:
search
