### ISSUE TITLE
Extremely large SVG exports, intermittent

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#201]
In the development branch, occasional SVG exports will be extremely large in size (e.g., ~10MB).

We cannot reliably reproduce this issue and are exploring ways to do so.

**Comment by jaywokim** [comment]
took the rule out of the nested for loops

**Comment by jaywokim** [comment]
I see this copied thousands of times:
nodes path.selected { stroke: rgb(255, 131, 0); stroke-width: 4px; }
from downloaded problem svg file
