### ISSUE TITLE
NN still broken

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#206]
Applying NN still fragments network
Before 
![image](https://user-images.githubusercontent.com/33426295/78036036-d7d9eb80-7337-11ea-9b18-85c645f5751e.png)

After NN filter:
![image](https://user-images.githubusercontent.com/33426295/78036130-f344f680-7337-11ea-9f4d-06a39591cc24.png)

**Comment by jaywokim** [comment]
processing edge list and node list as source files:
Demo_outbreak_EdgeList.csv
Demo_outbreak_NodeList.csv
produces distance matrix of all zeros for node 81
this causes error in MST routine
put in code that checks for all zero row and skips it.

**Comment by jaywokim** [comment]
fix deployed to DEV

**Comment by jaywokim** [comment]
console showing MST running twice, why?

**Comment by jaywokim** [comment]
edge case: when node ID is not represented in the edge list , MST was failing when network was creating a virtual node for the node id in the edge list.
