### ISSUE TITLE
Aggregation table unknown/null field blank

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#207]
Would be helpful for reports if any variable where there's no data available  shows up with 'unknown' in the aggregation table. It's currently blank.
![image](https://user-images.githubusercontent.com/33426295/78036887-d1983f00-7338-11ea-9c1d-afcde4ade400.png)

**Comment by ells** [comment]
Please set to the string 'empty' when a value is not present. If there are issues presented by this solution, please reach out.
