### ISSUE TITLE
Physics tree- changing tree type makes tree disappear

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#208]
Default display is weighted dendrogram. When I changed type to tree; tree disappeared. Changing it back to weighted dendro did nothing. When I hit the center button the image below showed up.
Had to close view tab and re-opn whereupon it opened again as a weighted dendrogram.
![image](https://user-images.githubusercontent.com/33426295/78078675-a46b8100-7378-11ea-9e22-bafea0dac2c5.png)

**Comment by jaywokim** [comment]
default value not initialized physics-tree-branch-length": 50
also the view specific menu was not defaulting to the correct tab
