### ISSUE TITLE
Initial display on Physics tree settings(Tree tab) is not as expected

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#209]
When you click on settings in the physics tree, this is what you should see
![image](https://user-images.githubusercontent.com/33426295/78078904-0fb55300-7379-11ea-93f9-08347e8070b7.png)

However, what you actually see when you open physics tree is this:
![image](https://user-images.githubusercontent.com/33426295/78078983-33789900-7379-11ea-9f29-000936064074.png)

Clicking on branches tab, and then back to tree tab gives the settings for tree (first image).

**Comment by jaywokim** [comment]
fixed in this issue
Physics tree- changing tree type makes tree disappear #208 
[145e033 ](https://github.com/CDCgov/MicrobeTrace/commit/145e033071bcbe67d923e841d0556196b5cf4607)
