### ISSUE TITLE
Enhancement request - have ability to sort counts in keys

### ISSUE THREAD

**Issue by billswitzer2** [CDCgov/MicrobeTrace#211]
Instead of dragging the key IDs and associated counts to sort them we should be able to select and up or down arrow to automatically do that.

**Comment by ells** [comment]
done

**Comment by billswitzer2** [comment]
Yeehah!

**Comment by jaywokim** [comment]
apply sort to the link legend

**Comment by billswitzer2** [comment]
Sweet!
