### ISSUE TITLE
highlighting a node in 2D does not bring it to top of table view

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#213]
highlighting a node in 2D view is supposed to force that node to the top of the table view.
Node is highlighted in table, but does not float to top. Similarly, searching for a node ID highlights it, but does not float it to the top.

**Comment by ells** [comment]
It makes the table much easier to use and it is mentioned in our manual explicitly, so it is a dealbreaker.

**Comment by jaywokim** [comment]
freezing too many nodes is crowding the page and losing the scroll bar
