### ISSUE TITLE
Link Color 'forgotten' after tiling map

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#222]
This occurs in the dev branch and is readily demonstrated with both the demo data set and the KCDC/COVID-19 data set. Please follow these steps to reproduce:

1.) Load a network with edge and node list. The edge list must have a categorical type column. The node list must have geocoordinates (either ZIP or lat-lon will suffice).
2.) Color the links according to a categorical 'type' variable
3.) Next, generate a map in the map view. You will see that, as expected, the colors have propagated to the map view.
4.) Finally, tile the map view adjacent to the network view. You will see that the link colors have been set back to default for both map and network views. This is also reflected in the global settings menu.

**Comment by jaywokim** [comment]
initialize linkColorVariable based on session state
