### ISSUE TITLE
Bubbles splits up and re-forms each time one selects a node in tiled view

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#224]
This happens when the two views are in separate tabs as well as when they are tiled in the same window. When 2D is next to Bubble view  and multiple nodes are selected in 2D, selection propagates to Bubbles, but the Bubble network splits and re-forms each time that happens- visually jarring and 508?

**Comment by jaywokim** [comment]
using the wrong id parameter .id instead of ._id
