### ISSUE TITLE
Saving and re-opening issues

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#239]
Tried saving a file after I made distance threshold changes, and mapped variables. The changes are reflected in the new session, however the network looks weird. In the pic attached, 
A. My original network. demooutbreak.csv edge list and node list. threshold changed to 0.006. Link width sized by distance, nodes colored by primary drug. Map view was open, set to zip.
B. Opening view when I opened saved microbtrace file. 
C. When I centered it. If I played with node size and link length, it made it seem more normal looking, but still does not look like original
![May11SaveIssue](https://user-images.githubusercontent.com/33426295/81721573-1215cd00-944e-11ea-8b2e-21690891b279.jpg)

**Comment by jaywokim** [comment]
this was an issue with the saved link length parameter. It was calculating a length multiples of the saved length using the wrong distance setting of forceLink instead of using force.force('link').distance for saved distance.
