### ISSUE TITLE
Gantt chart, cannot add data

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#240]
Currently, in the dev branch, when I navigate to the Gantt Chart view and click 'Add Button'...there is no response.

The console shows these errors:
![image](https://user-images.githubusercontent.com/1420108/81856555-f7ffeb80-952e-11ea-8049-4c531739dd02.png)

This behavior still occurs when in an incognito window and after clearing cache.

**Comment by jaywokim** [comment]
MT node ID will default to number type if there are no non number characters in the ID. The gantt view was expecting a string type for node id.
