### ISSUE TITLE
Google Analytics - Developer Exclusion

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#241]
Prior to COVID-19, we were able to reliably exclude traffic generated during development and testing by filtering traffic originating from a cdc.gov domain. The frequency of telework during COVID-19 is now obscuring our ability to distinguish traffic generated by development and testing. 

**Feature Request:** Ability to 'blacklist' ourselves from traffic metrics by Google Analytics. Implementation will likely require modification to MicrobeTrace and Google Analytics settings.

**Comment by jaywokim** [comment]
![GA](https://user-images.githubusercontent.com/55855925/84214026-32a66680-aa90-11ea-8197-4671334c4b6a.PNG)

**Comment by jaywokim** [comment]
use this filter pattern to capture MicrobeTrace.cdc.gov or microbetrace.cdc.gov
^(MicrobeTrace\.|microbetrace\.)?cdc\.gov$
