### ISSUE TITLE
Node Color Assignment + Histogram

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#242]
These bugs were identified when working with dummy files for COVID-19 training in the dev instance.

**They follow a very specific order to replicate. I will provide necessary files via email, but they should be replicable by other means as well...as these data were synthetically generated.**

1.) Take the node list, only the node list. 
2.) Generate an age histogram
3.) Color nodes by 'patient died of this illness?'
4.) Notice that the dead values are on bottom of the histogram (save this point for later), and the alive values are on top. 
5.) Also note that when I change the value for dead to red, the secondary color stays the same but the key changes to not match

![image](https://user-images.githubusercontent.com/1420108/82260773-db4b2580-992b-11ea-9c5e-5c32a7098596.png)

**Now let's move on to the point I asked you to save for later...and repeat steps 1-3.**

1.) Take the node list + three edge lists 
2.) Generate an age histogram
3.) Color nodes by 'patient died of this illness?'
4.) Notice that the dead individuals are now on top. Making the visualization substantially harder to interpret and see any patterns.
![image](https://user-images.githubusercontent.com/1420108/82260811-ec943200-992b-11ea-8d57-faf102bf5121.png)

5.) Also note that the color mismatch identified in Step 5 above does NOT occur. 

Overall, we've identified some kind of ordering bug in the histogram that changes its behavior based on whether an edge list is provided. This is because the histogram is initialized to the edge list distances. 

**When an edge list is provided, colors act properly but histogram sorting is not ideal.** 

**When an edge list is not provided, histogram sorting is ideal, but colors are broken.**

**Comment by jaywokim** [comment]
sorting applied to aggregate disrupting initial applied color order

**Comment by jaywokim** [comment]
ordinal and domain values were out of sync when sorting

**Comment by jaywokim** [comment]
needed to sort trace elements in traces array
