### ISSUE TITLE
Threshold increments in integers

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#243]
This behavior is documented currently on the dev instance, using the sequence generation method (rather than a standard file upload).

Note that initial distance settings are:
![image](https://user-images.githubusercontent.com/1420108/82495251-d36cbc00-9ab8-11ea-8a3a-f7ffa701b312.png)

The files are generated as such:
![image](https://user-images.githubusercontent.com/1420108/82495309-e8494f80-9ab8-11ea-90a9-a544f011a979.png)

The network is generated, and the threshold menu opened:
![image](https://user-images.githubusercontent.com/1420108/82495366-fe571000-9ab8-11ea-9e9a-bf2a8de9da57.png)

When clicking the up or down arrows on the threshold selector, the units jump in integers:
![image](https://user-images.githubusercontent.com/1420108/82495422-16c72a80-9ab9-11ea-9e5a-f53119fc9794.png)
![image](https://user-images.githubusercontent.com/1420108/82495485-28a8cd80-9ab9-11ea-9c3e-c29249832cd7.png)

The behavior persists, even when manually setting the threshold and re-engaging the up and down arrows.

**Comment by ells** [comment]
This behavior persists with the demo sequence file as well. Moving this up to high priority.

**Comment by jaywokim** [comment]
missing step parameter in input
