### ISSUE TITLE
Implement polygons feature using convex hulls with multiple foci 

### ISSUE THREAD

**Issue by jaywokim** [CDCgov/MicrobeTrace#253]
Implement feature that surrounds logically categorized nodes in a colored polygon using convex hulls methodology. 

require key
require support functions

**Comment by AABoyles** [comment]
An example of an alternative formulation of this feature (using WebCoLa): https://ialab.it.monash.edu/webcola/examples/smallgroups.html

**Comment by billswitzer2** [comment]
Cool, thanks for sharing!
