### ISSUE TITLE
Save custom colors

### ISSUE THREAD

**Issue by odb8-kt** [CDCgov/MicrobeTrace#255]
In a previous version there was the option to save your custom colors. I think this has been removed in the latest version meaning each color has to be entered each time it will be used. Would it be possible to add this save custom color feature back in? It helps speed up color selection. Here's the window I mean:
![image](https://user-images.githubusercontent.com/68611358/88208953-f8e48600-cc1f-11ea-8d72-435a6fb33049.png)

**Comment by AABoyles** [comment]
So, MicrobeTrace doesn't actually implement a colorpicker (the widget in the screenshot). Instead, it just uses what is the default for the user's browser/operating system. That looks like the Windows colopicker. Not sure what would've changed to cause your custom colors to disappear--maybe your browser or OS got an update that broke it? Either way, I don't think there's anything we can do on our end.

**Comment by odb8-kt** [comment]
OK, thanks.  For info, here's what I see in Google Chrome:
![image](https://user-images.githubusercontent.com/68611358/88222573-2d623d00-cc34-11ea-8821-f55464d94b03.png)

Interested to know if you see the same thing?

**Comment by billswitzer2** [comment]
I DO

**Comment by AABoyles** [comment]
Yeah, interesting. I can't find proof for this, but Chrome 84 dropped on 2020-07-14. I bet that's when they rolled out this modified colorpicker, which is why it cropped up recently..
