### ISSUE TITLE
Timeline: Nodes coming from link lists (without dates) not rendered 

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#265]
![image](https://user-images.githubusercontent.com/33426295/93224838-8f748580-f73f-11ea-9d9b-2f27c308fb87.png)
Ells had a temporary workaround. But that is not sustainable.

**Comment by AABoyles** [comment]
Simplest solution: default dates to the earliest date in the dataset. Nodes with null dates should always be visible.
Nuanced solution: default dates to the node's earliest neighbor. This is going to be super complex in implementation.
