### ISSUE TITLE
Key box moves around when distance threshold is changed

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#267]
When nodes/ links are colored by variables, and key is displayed, the key box moves to random places on the screen (does not stay on right hand side) when the distance threshold is changed. Modified column headers on key box also default back to original after threshold is changed. 
Details below:
1. Render network with metadata and select node color by risk factor and node shape by gender.
 
![KeyBug1](https://user-images.githubusercontent.com/33426295/93244769-3c5afc80-f758-11ea-8f21-6c42031f15fc.jpg)

2. Pinned 3 keys in place and removed “node” from key name i.e. change “Node Gender” to “Gender” and “Node Risk Factor” to “Risk Factor”:
 ![KeyBug2](https://user-images.githubusercontent.com/33426295/93244775-3d8c2980-f758-11ea-89bf-9e9e70bd0134.jpg)

3. Changed distance settings (filtering threshold) and select done. Keys move and “Node” added back to key title. Noticed this only happens when I edit the key title. May also change variable names back to default too i.e. After changing Idu to IDU it defaults back to Idu.
![KeyBug3](https://user-images.githubusercontent.com/33426295/93244777-3d8c2980-f758-11ea-9286-edbc376bc552.jpg)

**Comment by AABoyles** [comment]
> Noticed this only happens when I edit the key title. May also change variable names back to default too i.e. After changing Idu to IDU it defaults back to Idu.

Yes, I expect that this should happen. @mchiuw is on it!

**Comment by billswitzer2** [comment]
Great!
