### ISSUE TITLE
Polygon settings- color of all polygons should be the same

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#272]
Polygons should be colored the same.(light grey). If colored different colors, we need key functionality. Right now, just leave them all a uniform color
![image](https://user-images.githubusercontent.com/33426295/93643978-125f3f80-f9cf-11ea-9f88-2ebbaf0684cb.png)

**Comment by AABoyles** [comment]
Fixed [in Dev](https://cdcgov.github.io/MicrobeTrace/).
