### ISSUE TITLE
Map issue when I open a saved file

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#281]
When I open a saved file, the map seems to be overlaying repeated tile. See image below has US and Canada again below it.

![image](https://user-images.githubusercontent.com/33426295/94730628-8257b900-0331-11eb-8179-c36a2f5fed8c.png)

**Comment by AABoyles** [comment]
Was the tile basemap layer enabled in the session before you saved it, @ikb6? Were the outline layers turned on or off?

**Comment by ikb6** [comment]
Basemap layer was enabled, not sure of outline . When I opened the file, went to online, turned the basemap to hide and then back to show, the duplicate disappeared, but the names were hidden, and then when I turned on Satellite to Show\, it appears in this weird superimposed way

![image](https://user-images.githubusercontent.com/33426295/94941469-eb127300-04a2-11eb-9065-711c4e9f5b94.png)

**Comment by roxycintron** [comment]
@mchiuw was this issue solved?

**Comment by wje7-cdc** [comment]
Yes. It should be on DEV.

**Comment by wje7-cdc** [comment]
I just tested again and it's on DEV already.
