### ISSUE TITLE
Unable to export heatmap as .csv

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#283]
when using a sequence file in MT, would like to use the 'export as csv" feature in Heatmap view to export a distance matrix. It does not work. Just spins and freezes.

**Comment by AABoyles** [comment]
Oh! Bit of history here. The heatmap used to be populated by a data structure that was a direct analog to the heatmap (`session.data.matrix` was an array of arrays of floats). Then we wanted a little more flexibility, so we converted it to an Object mapping Node ID (source) to Objects mapping Node ID (target) to link object. This is very, very fast to traverse, but can't be consolidated into a text CSV using [the current approach](https://github.com/CDCgov/MicrobeTrace/blob/master/components/heatmap.html#L266). Should be a very light lift to resolve, though.

**Comment by ikb6** [comment]
Thanks Tony! I will conveniently absorb only the last line of your comment and leave the rest to Michael. :) Thanks!

**Comment by wje7-cdc** [comment]
Thanks, Tony! I will look into it.
