### ISSUE TITLE
color swap with two link files

### ISSUE THREAD

**Issue by AndrewLangvt** [CDCgov/MicrobeTrace#292]
When I save a microbetrace file and then re-load that build, if I have two separate link files, the color scheme swaps for the two files. 
How I built it:
File 1 links color Blue
File 2 links color Green
How it looks when I reload the file:
File 1 links color Green
File 2 links color Blue

This may seem menial, but I will often color the more abundant link-type a lighter color, while the less-abundant I go with a darker color to allow for easy visualization of both. It's a bummer when these get swapped. Obviously, the way around is to simply swap them on the outset and save the build with the opposite color scheme I really want. It works, but isn't ideal.

**Comment by AABoyles** [comment]
Hey @AndrewLangvt! You're totally right, that's a huge pain in the neck. To help us replicate the issue, do the link files share the same sets of headers? Or does one have a variable that the other doesn't have, and then you color by that variable to achieve the color distinction? Or are you just coloring by the `origin` variable?

**Comment by AndrewLangvt** [comment]
I am just coloring by the origin variable. I have seen this activity when
my two files have the same headers, and when they have different headers.
