### ISSUE TITLE
Replace d3.forceManyBody with d3.forceManyBodySampled

### ISSUE THREAD

**Issue by AABoyles** [CDCgov/MicrobeTrace#302]
d3.forceManyBody recomputes a quadtree on every tick. This is an expensive operation, and we can get a pretty good speedup (~30% improvement) by doing it less frequently. [d3-force-reuse](https://github.com/twosixlabs/d3-force-reuse) sets this frequency to a static once-per-13 frames, with [minimal cost to layout quality](https://bl.ocks.org/rpgove/ecee35052e3e81126dcefff134c06dae).

**Comment by wje7-cdc** [comment]
Ells, can you update this issue based on our meeting today?

**Comment by wje7-cdc** [comment]
Tried both d3.forceManyBodyReuse and d3.forceManyBodySampled but decided not to replace existing d3.forceManyBody.
