### ISSUE TITLE
Coloring of nodes is "forgotten" when saved

### ISSUE THREAD

**Issue by AndrewLangvt** [CDCgov/MicrobeTrace#312]
I'm primarily working in the dev version, though this issue is seen in the production version as well. 

When I color nodes by a given attribute, save the microbetrace build, and re-import that build, the coloring is lost. Is this done for a particular reason? It would be helpful for this to be retained when I am passing a build off to an Epi.

**Comment by AABoyles** [comment]
Thanks, @AndrewLangvt! Definitely not intentional. @mchiuw

**Comment by wje7-cdc** [comment]
Thanks for raising the issue. Will look into it...

**Comment by ells** [comment]
Thanks @AndrewLangvt , can you give me an idea of how many color categories you're using?

**Comment by AndrewLangvt** [comment]
@ells, it was 15-20 different colors.

**Comment by wje7-cdc** [comment]
@AndrewLangvt, fix has been implemented. Please give it a try.

**Comment by AndrewLangvt** [comment]
Boom!! Thanks for working this so quickly! :-D

**Comment by billswitzer2** [comment]
Great job Michael!
