### ISSUE TITLE
Random date inserted in cells that have null values

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#315]
Whenever there is a null value in the node list, MT seems to enter a random 1969 date in that cell in any view that has rows and columns (eg Table, Aggregate, cross tabs, etc,). It enters **NaN** in the distance column. This is an issue with a dataset with place nodes. All place nodes will be missing all other demo data. See pic below. I used the COVID dummy data file in Teams

![DAte_in_Null_field](https://user-images.githubusercontent.com/33426295/110515870-de8be980-80d6-11eb-8c53-f43195049055.JPG)

**Comment by roxycintron** [comment]
Bill found random dates are still inserted in cells with null values

**Comment by mossy426-cdc** [comment]
Can anyone send me an example dataset that doesnt work?  If it's confidential you can email me, otherwise you can just attach it to this ticket.

**Comment by mossy426-cdc** [comment]
To keep timeline in tact, will leave table cells with date of first date in the timeline.
