### ISSUE TITLE
Research + Setup + Walkthrough Project Management Tool

### ISSUE THREAD

**Issue by mossy426-cdc** [CDCgov/MicrobeTrace#332]
Now integrating our zenhub with github, we can use this as an excellent project management tool.  With it we no longer need to:

- Draft emails about bugs
- Draft emails with attachments/images about a specific issue
- Draft regular emails of updates with development progress
- Keep track of various email threads regarding different issues
- Maintain various excel sheets on different issues

With it, we can:

- Document everything in such a way that can be easily accessed, filtered, and searched for 
- Update issues that trigger notifications, not requiring drafting emails to be sent, or begin threads of emails
- We can comment on issues directly with participants being notified, and in a way that can be looked back on in case of need for clarification in the future for how we came to a resolution
- Easily track and identify tasks/issues based on priority, type, complexity, etc.
- Have complete transparency between dev, qa, etc.
- Define and categorize user stories that will be used as metrics to test against and come to agreed upon acceptance criterias 
- Make it easier for onboarding others and/or understanding how the application should work
- Assess rate of completion based on complexity of task
- Make better projections for completion time of tasks
- Become more partner friendly when other orgs/apps would like to collaborate with us
- Centralize and Structure our issues/tasks in a way that makes meetings much more efficient

**Comment by roxycintron** [comment]
Awesome!
