### ISSUE TITLE
Website down (503 Service Unavailable)

### ISSUE THREAD

**Issue by odb8-kt** [CDCgov/MicrobeTrace#334]
Tried to access MicrobeTrace on 03/26/21 and 03/28/21. Both times received 503 Service Unavailable message. Cleared cache, didn't resolve. Tried on a separate computer/internet service, didn't resolve.

![image](https://user-images.githubusercontent.com/68611358/112755210-b7c22400-8fad-11eb-974f-04136190fcb3.png)

**Comment by MMirabito** [comment]
Please try again it should be fixed server was twisted and required a reboot.

Thanks
max

[https://microbetrace.cdc.gov/MicrobeTrace/](https://microbetrace.cdc.gov/MicrobeTrace/)

![image](https://user-images.githubusercontent.com/23298288/112773688-e3242d80-9004-11eb-85bf-101a6369a54e.png)

**Comment by odb8-kt** [comment]
Thanks, working now.
