### ISSUE TITLE
Test Distance Matrices

### ISSUE THREAD

**Issue by frankambrosio3** [CDCgov/MicrobeTrace#347]
Testing the three distance matrices provided by Jason to see if they load in MicrobeTrace.

**Comment by frankambrosio3** [comment]
Started loading files into MT at 5:37, currently still loading

**Comment by frankambrosio3** [comment]
1 hour later, MicrobeTrace has still not loaded the distance matrices.

**Comment by frankambrosio3** [comment]
Issue is with the column and row names having special characters. Solved by replacing names with numerical aliases.

**Comment by frankambrosio3** [comment]
Confirmed that the issue was the special characters in the column headers (sample ID's). Solved by replacing the ID's with numerical pseudonyms. In the future I would recommend against using any special characters (besides underscore) in sample ID's for a distance matrix, otherwise use pseudonyms and a lookup table.

**Comment by billswitzer2** [comment]
Thanks Frank. Can you share some of the special characters that caused this issue?

**Comment by mossy426-cdc** [comment]
We should include these conditions in manual as per discussion in Dev meeting.  @ikb6
