### ISSUE TITLE
Replace Node Shapes with PNG Images

### ISSUE THREAD

**Issue by frankambrosio3** [CDCgov/MicrobeTrace#351]
For the vital conditions project I would like to replace the nodes with png images provided by our colleagues. I am sure that this will have applications in other projects to represent node types (people, buildings, etc.). Currently I am just modifying the final image in powerpoint but it would be awesome if I could up load a set of images and link them to the shapeby function on MT. It would also be fantastic if these images could be used to label polygons. Please let me know if you would like to chat about this one, or if you would like example files.![Basic-Needs.png](https://images.zenhubusercontent.com/606f6d7793561a97a753df3e/455c7664-a09d-413f-8ebd-cfaa1637422a)

**Comment by billswitzer2** [comment]
Great idea!

From: frankambrosio3 ***@***.***>
Sent: Wednesday, April 14, 2021 10:03 AM
To: CDCgov/MicrobeTrace ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CDCgov/MicrobeTrace] Replace Node Shapes with PNG Images (#351)


For the vital conditions project I would like to replace the nodes with png images provided by our colleagues. I am sure that this will have applications in other projects to represent node types (people, buildings, etc.). Currently I am just modifying the final image in powerpoint but it would be awesome if I could up load a set of images and link them to the shapeby function on MT. It would also be fantastic if these images could be used to label polygons. Please let me know if you would like to chat about this one, or if you would like example files.[https://camo.githubusercontent.com/5494fc1502cb41b91bc11b33f9a0db202992db4d650d694c37bbe03111635203/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630366636643737393335363161393761373533646633652f34353563373636342d613039642d343]<https://camo.githubusercontent.com/5494fc1502cb41b91bc11b33f9a0db202992db4d650d694c37bbe03111635203/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630366636643737393335363161393761373533646633652f34353563373636342d613039642d343133662d386562642d636661613136333734323261>

**Comment by frankambrosio3** [comment]
We have received a set of the icons in SVG format from our Vital Conditions colleagues. Please let me know if/when you need access to these images.
