### ISSUE TITLE
Styling File Not Being Applied

### ISSUE THREAD

**Issue by mossy426-cdc** [CDCgov/MicrobeTrace#355]
I have provided a fix.  The styling file would change the session variables, but there were no triggers to update the actual network.

**Comment by billswitzer2** [comment]
Great, thanks!

From: mossy426 ***@***.***>
Sent: Thursday, April 15, 2021 12:45 PM
To: CDCgov/MicrobeTrace ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CDCgov/MicrobeTrace] Styling File Not Being Applied (#355)


I have provided a fix. The styling file would change the session variables, but there were no triggers to update the actual network.

**Comment by mossy426-cdc** [comment]
Moved back to in progress after QA review found node color was not being applied correctly.

**Comment by mossy426-cdc** [comment]
It seems to apply or not apply styling correctly depending on the data set.  Investigating further to determine the cause.

**Comment by ells** [comment]
In most prior experiences, when we have a data-specific issue, it is (1) a weirdly formatted value or (2) a namespace collision issue.

So if the names of suspect dataset are generic and overlap with our namespace...we might want to start there.

**Comment by mossy426-cdc** [comment]
Got it, thanks for the tip!

**Comment by billswitzer2** [comment]
Still not working correctly with my OH-KY data. Used same input files but styles not applied and networks differ. WIll have to do a screen share to show the differences.

**Comment by ells** [comment]
@billswitzer2 Can you describe what isn't being applied or is it all styles?

**Comment by billswitzer2** [comment]
None of the styles (node color, node shape) is being applied. But the network is also different.

**Comment by ells** [comment]
@billswitzer2 The network structure is different (node/edges)? or the network layout is different?

**Comment by billswitzer2** [comment]
Both. Let's review with some screen time tomorrow.

**Comment by mossy426-cdc** [comment]
Sounds good.   Let's check it out in the standup.

**Comment by mossy426-cdc** [comment]
Had a meeting with Bill going over the issue.  It works as expected, but a couple items to note:

- The styling will only apply properly if the new files are launched with the same typing as the original.  For example, if dataset X was launched as a node list, styling will not work if dataset X is launched as a linked list for another session. 
- @ikb6 We should document this in the instructions where applying styling is outlined as per Bill/Ells. 

Moving to done as issue has been resolved.
