### ISSUE TITLE
User-provided Map Layers

### ISSUE THREAD

**Issue by AABoyles** [CDCgov/MicrobeTrace#36]
The map view includes an offline, hyper-secure, low-res map of Countries, States, and counties. It also contains (only slightly) less secure tile maps of roads and satellite images. However, some users might want to be able to import their own geospatial data. For example it might be beneficial to show the [Boroughs of New York](https://github.com/dwillis/nyc-maps/blob/master/boroughs.geojson). Including this data in the app by default doesn't make a lot of sense, but enabling users to add it to the map themselves does. Here's how we do it:
1. Add a File input somewhere in the UI of [`components/geo_map.html`](https://github.com/CDCgov/MicrobeTrace/blob/master/components/geo_map.html#L139)
2. Add javascript to read a file when one is added to the File Input, parse it as JSON, [generate a new layer with it](https://github.com/CDCgov/MicrobeTrace/blob/master/components/geo_map.html#L313), and add it to the map.

**Comment by DanielJDufour** [comment]
Anyone working on this?
