### ISSUE TITLE
Cluster- node listing table

### ISSUE THREAD

**Issue by kjp43** [CDCgov/MicrobeTrace#360]
Hello,  

Is there a downloadable output that will list the names of each sequence (or node ID) in a given cluster ? For example, in the cluster table attached,  is there a way to retreive a listing of node ID as shown in column H (inserted by me) other than working through all of the source/target listings in the links data table?
[Cluster-node table example.xlsx](https://github.com/CDCgov/MicrobeTrace/files/6351605/Cluster-node.table.example.xlsx)

Thanks!
Kerri

BTW.. this program is amazing! :)

**Comment by billswitzer2** [comment]
Hi Kerri,
Thanks for using our tool and your sharing your experience. The file you sent looks like the link list that was downloaded from the Table view in MicrobeTrace. In that same view you can download the node list which will include the cluster IDs in the column “cluster”. You can then then sort that column by smallest to largest and then highlight identical values using conditional formatting in excel to find all the clusters with more than one sequence and their IDs.
Hope this helps.
BTW, what is your affiliation?
Thanks,
Bill
William M. Switzer, M.P.H.
Molecular Epidemiology and Bioinformatics Team Lead
Laboratory Branch
Division of HIV/AIDS Prevention
Centers for Disease Control and Prevention
1600 Clifton Road, Mailstop H18-2
Atlanta, GA 30329
404-639-0219 (Phone); 404-639-1174 (FAX)
***@***.***


From: kjp43 ***@***.***>
Sent: Wednesday, April 21, 2021 10:33 AM
To: CDCgov/MicrobeTrace ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CDCgov/MicrobeTrace] Cluster- node listing table (#360)


Hello,

Is there a downloadable output that will list the names of each sequence (or node ID) in a given cluster ? For example, in the cluster table attached, is there a way to retreive a listing of node ID as shown in column H (inserted by me) other than working through all of the source/target listings in the links data table?
Cluster-node table example.xlsx<https://github.com/CDCgov/MicrobeTrace/files/6351605/Cluster-node.table.example.xlsx>

Thanks!
Kerri

BTW.. this program is amazing! :)

**Comment by kjp43** [comment]
Thanks so much for getting back to me so quickly!  What I am looking for is a line list that details the cluster # and node IDs within that cluster (as opposed to node ID and cluster # it belongs to).  Ultimately I'm trying to find a way to extract association data as sets rather than going through one cluster at a time (i.e.  cluster 491 is made up of the following nodes[MH403, MH404, MH47, 5440, 5626]).  It seems the method listed below would also be looking through cluster by cluster, or maybe I'm misunderstanding?

What I'm trying to make is a listing like this table below (cluster would be the # assigned by MicrobeTrace and cluster members are the NodeID).  While it is true that I can get this info in the node and link lists,  I was just wondering if there was an easier way to get the following output.  I've been generating in excel (semi manually). Does MicrobeTrace offer an output like this specifically?

cluster
Cluster members
18
1468_16, 1468_17, 1468_18
33
2409,  3750, 4552
42
2903_08, 2903_08b, 2903_09
47
3010_18, 3010_20
62
3420, 3554, 3880
82
MH225, 3500
94
MH201, 3563, 5136
110
4514, MH112, 6124, 4511, 3873, 4637, 4386, 4515, 4680, MH13, MH202, MH295, 3867, 4514, 4669, MH246, 4977, 6249, 5022, MH352, 5522, MH329, 4422, MH222, 3622, 3775, MH311, MH305

Thanks again for your help!

Kerri


Kerri J. Penrose, M.S.
Research Project Manager
Parikh Laboratory
University of Pittsburgh
ph 412.383.3922

**Comment by billswitzer2** [comment]
Hi Kerri,

Thanks for your clarification. Unfortunately, MicrobeTrace cannot do that directly at this time. We currently use Excel for extracting cluster level data. However, that is a great idea and we’ll add that as an issue to address. Our success depends on users like you!

Thanks,

Bill

**Comment by mossy426-cdc** [comment]
Hi Kerri!  You asked and we listened.  When you have what you'd like to save in microbetrace, navigate to file -> save -> check "by cluster" and you should received a zipped folder of the following structure:
- 1 folder per cluster - called "cluster-ID" (depending on the id of the cluster)
- - Within each cluster folder, the corresponding node and edge list files will be
- 1 folder called "dyads" which will list all the dyad nodes in a single node list as well as all the dyad edges in a single edge list
- 1 folder called "singletons" which will contain a node list since there are no edges.

Please note this has just been implemented and we are performing various tests, but so far everything seems to be in order. Give it a shot and let us know if you have any feedback :) Thanks!

@kjp43

**Comment by kjp43** [comment]
This is so awesome!!!  Thanks so much!

I will certainly check this out 😊

Have a great weekend!

**Comment by mossy426-cdc** [comment]
No problem.  Have a great weekend!

**Comment by kjp43** [comment]
Hi!

So sorry for the delayed response.  I'm having trouble finding how to retrieve this output.  Can you be a little more specific? Or maybe send screen shots?  What view would I need to be on, etc.  I'm using Chrome,  so not sure if that has any impact,  I'm not seeing anywhere to select by cluster.

Thanks!
Kerri

**Comment by ells** [comment]
Hi Kerri, there may be two issues here:
1.) You may be looking at our production environment (https://microbetrace.cdc.gov) which is a bit out of date for new things. If so, try here: https://cdcgov.github.io/MicrobeTrace

2.) If you are using the development site, then you can find it here:
![image](https://user-images.githubusercontent.com/1420108/118725640-34c78800-b7fe-11eb-94b0-85e04705c8b6.png)

This is available after clicking File -> Save on the main menu.
![image](https://user-images.githubusercontent.com/1420108/118725700-4a3cb200-b7fe-11eb-95db-b4ca3b805769.png)

**Comment by kjp43** [comment]
That's it!  Working from GitHub was the solution.

Thanks so much Ellsworth!

Best,
Kerri

**Comment by ells** [comment]
Wonderful! Glad to help!
