### ISSUE TITLE
Map License

### ISSUE THREAD

**Issue by frankambrosio3** [CDCgov/MicrobeTrace#382]
The current leaflet maps package is using the MapBox collection of maps. We would like to switch this to OpenStreetMap in order to avoid licensing fees incurred through the usage of the for-pay maps service.

**Comment by mossy426-cdc** [comment]
Switched to OpenStreeMaps tile server, but language label for most countries is local (not to the user, but to the country), so it's not a sufficient solution.

Have looked at OpenMapTiles but would require  to host our own server to serve our own tiles or use the mapbox-gl plugin which isn't the best solution either.. 

Currently looking at basemaps.carto.cdn.com which is currently the most optimal solution.  Have pointed to the server and can get the map tiles with the correct languages... Ensuring license is CC BY.

**Comment by frankambrosio3** [comment]
https://creativecommons.org/licenses/by/3.0/

https://www.openstreetmap.org/#map=4/38.01/-95.84

https://www.openstreetmap.org/copyright

https://stamen.com/
