### ISSUE TITLE
Map Marker Clustering

### ISSUE THREAD

**Issue by AABoyles** [CDCgov/MicrobeTrace#39]
**Background**
Understanding the spatial distribution of cases is fundamental to understanding the underlying cause. While MicrobeTrace currently renders data on the map, it succumbs to overplotting issues. We have a number of workarounds (transparency and jitter functions), but ultimately, we'd like to use node size to represent density of cases for a particular location. This turns out to be a harder problem than it would initially seem.

**Open Task Description**
MicrobeTrace has a rudimentary [map view](https://github.com/CDCgov/MicrobeTrace/wiki/Map). At present, it shows nodes exactly where their locations are tagged, which makes [overplotting](https://www.displayr.com/what-is-overplotting/) a big problem (typically, users don't have high precision Lat/Lon data, but low precision geolocations like zipcodes, which will all be drawn on exactly the same spot on the map). Jittering and transparency controls are two existing solutions, but they don't seem to satisfy anyone. Instead, let's implement a [clustering-based approach](https://leafletjs.com/plugins.html#clusteringdecluttering).

To accomplish this:
1. Add the [clustering library](https://github.com/Leaflet/Leaflet.markercluster) to MicrobeTrace's dependencies and load it in the [`index.html`](https://github.com/CDCgov/MicrobeTrace/blob/master/index.html#L419) file.
2. Copy the salient code from [a simple example](https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html) and adapt it to work with [`components/geo_map.html`](https://github.com/CDCgov/MicrobeTrace/blob/master/components/geo_map.html#L481)

Stretch goal: Add a UI to toggle clustering on and off.
Double Stretch goal: Check to see if links are visible on the map. If so, toggle clustering off.

**Comment by jbixon13** [comment]
I've used the markercluster plugin through the leaflet API in R, is there any reason you wouldn't use that plugin to solve this issue? Or is the difficulty here more in getting it working within the existing script you've built, not so much the functionality of the plugin itself?

**Comment by AABoyles** [comment]
Definitely the latter. We don't need to build the functionality, we just need to hook up the library and set up UI controls so it interacts with MicrobeTrace in a sane way.

**Comment by jbixon13** [comment]
Its default behavior/implementation is pretty intuitive, do you know where issues are coming up in the implementation? Not saying it's that simple, just wondering why if you were able to build the rest of something this complex this is causing issues? I'm not as familiar with js as I'd like so forgive if I'm oversimplifying. (or is it an issue of time prioritization?) I'd like to take an attempt at it but want to make sure I'm understanding correctly.

**Comment by jbixon13** [comment]
Also, what would be the best way to test changing features within the components/geo_map and to see what it does to the map? I'd assume using something like a text editor wouldn't work for seeing changes to the web app.

**Comment by AABoyles** [comment]
Hey Jason! It's a feature request, not a bug report. Implementing it isn't really a problem, I just haven't gotten around to it yet (you may have noticed [I have a few issues](https://github.com/CDCgov/MicrobeTrace/issues) 😂). Please do take a stab at it and let me know how it goes!

BTW, you're going to need some test data. The `atlanta_dummyNodeList.csv` in Module 2 of [the demo data](https://github.com/CDCgov/MicrobeTrace/raw/master/demo/MicrobetraceDemoData.zip) has `LAT` and `LON` columns. Load that dataset into MicrobeTrace, go to View/Map, and then select LAT and LON from the respective dropdown menus and you should get the nodes on your map. From there, good luck!
