### ISSUE TITLE
Warning Message for IE Users

### ISSUE THREAD

**Issue by AABoyles** [CDCgov/MicrobeTrace#40]
**Background**
Internet Explorer has not been actively supported by Microsoft for a number of years. It has hobbled along beyond its life cycle and lingers on as a relic of the past. That being said, MicrobeTrace does not currently warn Internet Explorer users of its incompatibility. We require a banner that detects Internet Explorer and warns users that they should join the 21st century. 

**Open Task Description**
We should really add a banner warning people that their [terrible](https://www.wired.com/2016/01/the-sorry-legacy-of-microsoft-internet-explorer/), [unsupported](https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support), non-standards-compliant browser is rubbish and they should switch to _literally anything else_. Not because I have an axe to grind, mind you, but because [MicrobeTrace does not and will never work on Internet Explorer](https://github.com/CDCgov/WebMicrobeTrace/wiki/Internet-Explorer).

**Comment by adamjubert** [comment]
I'll take a look at this issue.

**Comment by nagano564** [comment]
I am working on a version right now.
