### ISSUE TITLE
MT DEV/PROD: Calculated Tree from Fasta

### ISSUE THREAD

**Issue by roxycintron** [CDCgov/MicrobeTrace#417]
**Problem:**
When a FASTA file is loaded in classic MT, the phylogenetic tree constructed is wrong.

**To see the MT DEV/PROD calculated tree:**
1. Load the node csv and fasta files
2. Click Launch 
3. Go to View and select Phylogenetic Tree
4. View the wrong calculated tree (image below) - Note the random distribution of the SARS-CoV-2 lineages

![image.png](https://images.zenhubusercontent.com/607a02e552f324d422b2175a/18a7c631-fbf7-42c0-9251-85cc9e41444c)

**Expected behavior**
**Use Reagan's JAVA code that we tested in Angular**. The correct tree is shown below.

![image.png](https://images.zenhubusercontent.com/607a02e552f324d422b2175a/4a9af7c6-6fb9-4972-b3c9-22d2f67c2295)

**Comment by ikb6** [comment]
tested this with my dataset, and it now seems correct
