### ISSUE TITLE
Help opens on top of current analysis

### ISSUE THREAD

**Issue by billswitzer2** [CDCgov/MicrobeTRACE#428]
Can we modify the code such that when a user selects the help link that a new window opens rather than opening in the current window?

**Comment by billswitzer2** [comment]
Can the code be modified such that a new window opens when a user selects "help" rather than it opening on top of the current window?

**Comment by mossy426-cdc** [comment]
@billswitzer2  Yes it can.  I'll make the adjustments.

**Comment by billswitzer2** [comment]
GREAT!

**Comment by mossy426-cdc** [comment]
@billswitzer2  Closing the issue now as it's in dev and working properly.
