### ISSUE TITLE
Multiple link types not being displayed

### ISSUE THREAD

**Issue by lizkrowlucal** [CDCgov/MicrobeTRACE#436]
Some links may have more than one type of link - for example, a contact could be a friend and also a classmate. It used to be these showed up with both colors as a dotted line, but right now it only shows up as a solid line - it just picks one and goes with that.

**Comment by mossy426-cdc** [comment]
Hi there, are you using the production or dev environment?  A push for a fix will be made to production soon.  If you are using dev, can you tell me the file extension and what types you select prior to launching? (I.e Link, node, matrix, etc.)

Here is a link to our dev environment just in case: https://cdcgov.github.io/MicrobeTrace/

**Comment by lizkrowlucal** [comment]
Broken in both - I used both and it didn’t work in dev either.

**Comment by mossy426-cdc** [comment]
Understood.  Can you provide any information on the file types as mentioned so we can replicate your issue?

**Comment by lizkrowlucal** [comment]
Csv file with edge data - names of cases (case_names) to names of contacts (value). Variable with type of edge (name) including things like schoolmate, family member, friend, etc

**Comment by mossy426-cdc** [comment]
Ok so all data is in one file? Thanks for the info.  We will get back to you soon

**Comment by lizkrowlucal** [comment]
Originally I had an edge list and a node list, but then cut it down to just the edge list to see if that was the issue

**Comment by lizkrowlucal** [comment]
I also noticed that it then collapses the links in the raw data such that in the original it will say Person A --> person B = classmate; person A --> Person B = sibling; but then in the table it collapses to just say one of those.

**Comment by mossy426-cdc** [comment]
Ok great, that helps narrow down the issue.  I am working on it today.

**Comment by mossy426-cdc** [comment]
For now, I believe you'll be able to achieve your desired functionality by using the two separate files like you had before.  If you navigate to settings -> styling tab -> Color Links By "Origin", you should see the dotted line for links having multiple types.  Please let me know if that works for you.

**Comment by Mossy1022** [comment]
I made it so that it should default to show link colors by origin (file source) in dev.  Within 15 minutes or so it should take effect.  Please let me know if that resolves your issue.  I would recommend sticking to the two file approach for now with each representing a different link type.

**Comment by lizkrowlucal** [comment]
This hasn't fixed the issue. The links are all in one file - I have color
by name. See below for example. When I put this in, microbetrace collapses
it to one link with the first appearance instead of showing it as a dotted
line.
[image: image.png]

**Comment by mossy426-cdc** [comment]
Ok, thanks for checking with one file, but please try with the original two separate files.  The dotted lines only appear when there when a link is referenced from multiple sources/files. That's how you can get multiple link types - not within the same file, otherwise it will collapse.  If that doesn't work, can you share your data set?  Or we can also get on a call if that would be easier.
