### ISSUE TITLE
Download by cluster- seems to stop working with larger datasets

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#441]
Could be a limitation of computational power of computer. Had a user (Christine Atherstone), with a larger dataset, she had around 410 clusters. When she tried download by cluster, it would just not do anything. Exporting link and edge lists from Table view for that same dataset worked fine.

I tried using an example dataset created by Reagan (attached). Prod worked fine (although a bit slower than usual, but acceptable).
However, when I tried in DEV, it did not work, and when I opened the console, I saw this error 

![ConsoleError_Filewith437clusters.jpg](https://images.zenhubusercontent.com/60873227d0d25c1fe3daadb1/37f554d7-e40d-478f-8dca-f1df42ce5610)

(https://images.zenhubusercontent.com/60873227d0d25c1fe3daadb1/194af1b3-17ae-4fe9-a332-28e830a5845a)

**Comment by ikb6** [comment]
The user sent her files. It's really large, and the console gives an error (this PROD, because she is using prod).
![error_console_Cluster bug](https://user-images.githubusercontent.com/33426295/142648744-2998cc51-508f-4a64-8e38-a9f297e78186.JPG)

**Comment by ikb6** [comment]
[link_fulldataset_noPII.csv](https://github.com/CDCgov/MicrobeTrace/files/7571259/link_fulldataset_noPII.csv)
[node_chacteristics_clean_noPII.csv](https://github.com/CDCgov/MicrobeTrace/files/7571260/node_chacteristics_clean_noPII.csv)

**Comment by mossy426-cdc** [comment]
@ikb6  I've tried in dev with the attached data set and it works in dev after the changes I pushed.  Please let me know if dev still does not work for you.

**Comment by ikb6** [comment]
@mossy426 . It works for me now in DEV! Thanks! I'll pass on to collaborator and have her try.
