### ISSUE TITLE
Hantanet- when  a test FASTA is loaded, threshold is displayed as SNPs

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#478]
When I load my sequences into HantaNet, distance threshold shows up as SNPs although Hantviruses ref set is loaded with TN93

 - Browser [Chrome]
 - Version [0.6.2]

![image](https://user-images.githubusercontent.com/33426295/155735535-2308ffbf-0167-4c72-a6e9-b2dfd58cc025.png)

**Comment by mossy426-cdc** [comment]
Clearing cache poses a fix, meaning it stores in local storage incorrectly at some point. Will look into it.
