### ISSUE TITLE
ANGULAR: Tooltip- allows only one variable

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#538]
We had the ability to add more than one field  for tooltips. Angular only allows one. Also, even in the regular MT version, it now only allows 2, when we were able add more than that before.

**Comment by ikb6** [comment]
This is an important feature- could you please address this? Thanks!

**Comment by mossy426-cdc** [comment]
Added multiselect tooltip to both nodes and labels.  When more than one tooltip selected, tooltip displays all selections in a table.
