### ISSUE TITLE
ANGULAR- Filtering by distance thresholds

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#541]
Not sure if the pre-loaded dataset is molecular or epi data. The node list contains seqs, so I assumed it was molecular. Adjusting distance thresholds breaks the network. 
Also, there is no way of seeing which files are loaded in the current session.

![Dist_Threshold.JPG]
(https://images.zenhubusercontent.com/60873227d0d25c1fe3daadb1/a94d8dce-8cb3-400b-b838-1a6c277ba0f6)

**Comment by ikb6** [comment]
![Dist_Threshold.JPG](https://images.zenhubusercontent.com/60873227d0d25c1fe3daadb1/55ed407e-20dd-4286-8bbe-ffd1fbc5b5d8)

**Comment by roxycintron** [comment]
Please also note that the histogram for distance cut-off is missing in Angular
![image](https://user-images.githubusercontent.com/71835013/200634965-14b7e7e2-d159-409c-b397-29ed75b75b2c.png)

**Histogram in MT Dev**
![image](https://user-images.githubusercontent.com/71835013/200635110-1f8caf09-97b6-4528-9fc7-66c816d30154.png)

**Comment by ikb6** [comment]
This is still broken. dropping the distance from 0.015 to 0.014 gets rid of links except one. Also, we need to mention what kind of data the pre-loaded session is, so that people will know what it they have loaded
