### ISSUE TITLE
ANGULAR- link labels show SNPS

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#543]
Again, I am not sure if this is a function of which data has been loaded; From what I know, the loaded set is HIV, where distances are TN93, and are expected to be 0.015 or lower. Here, all link distances show as integers when I turn on link labels.

**Comment by mossy426-cdc** [comment]
@ikb6  Can you provide me with this dataset?  Or dataset that has the same error?

**Comment by ikb6** [comment]
> @ikb6 Can you provide me with this dataset? Or dataset that has the same error?

This was a really old issue (july last year). You can close it since it seems to have been resolved at some point. I do not recall what files i used. I'll make ait a point to include file names in future issues
