### ISSUE TITLE
Arrows are not displayed on links while timeplayer is being used

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#546]
Pointed out by monkeypox group, so it is high priority (for presenting to leadership).

When they turn arrows on (in links settings tabs), then do Timeline, the arrows are no longer displayed. I tried on my end, and it looks like the **Show arrow** button seems to automatically toggle to off when you hit play. I say this because, if I have link settings open and hit **Show** again while Timeplayer is playing, a bunch if arrows show up on the already drawn links.

**Comment by mossy426-cdc** [comment]
It seems the issue was that directionality was never factored into the network render function as it wasn't needed prior to the timeline function.  I've updated the implementation for this and it seems to be working.  Please verify and I will close this issue.

**Comment by billswitzer2** [comment]
Thanks Evan!
