### ISSUE TITLE
Assigning color to column with many values

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#55]
When mapping color to a variable with many options (e.g., 15+):

Rows whose color-mapping is set to the same color as other rows with null values produces inaccurate results. 

**Stage 1:**
![Stage 1](https://user-images.githubusercontent.com/1420108/47318340-cdcb9d80-d619-11e8-8f2c-8eb726dfc284.PNG)

**Stage 2:**
![Stage 2](https://user-images.githubusercontent.com/1420108/47318363-db812300-d619-11e8-999e-c7eec30026f5.PNG)

**Comment by AABoyles** [comment]
I believe this was resolved awhile ago. Closing for now.
