### ISSUE TITLE
MT DEV/PROD: New arrows displaying after adding FASTA or Distance CSV files - TN93 or SNP metric

### ISSUE THREAD

**Issue by mossy426-cdc** [CDCgov/MicrobeTRACE#556]
Arrows in genetic links when there shouldn't be. Arrows in epi links display correctly.

**Desired Outcome:** Only show arrows from epi links in genetic-epi network overlay.

![image.png](https://images.zenhubusercontent.com/607a02e552f324d422b2175a/386a4c32-aa66-4bc1-870c-f90aac425893)

**Comment by roxycintron** [comment]
We fixed this issue only when fasta files are loaded. 

I modified this title to include removing arrows in genetic links when loading distance CSV files and the TN93 or SNP metric is used. **Note the error: arrows in genetic links (gray)**  The epi arrows are correct.

![image](https://user-images.githubusercontent.com/71835013/206799311-ffc71100-d135-40d3-b83a-37357161d55a.png)

**This network was created with a distance CSV file and the SNP metric**

![image](https://user-images.githubusercontent.com/71835013/206800109-e53ef42a-bc0f-498b-951d-dd36836a8f68.png)
