### ISSUE TITLE
ANGULAR: Ambiguity Threshold in Distance metric menu

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#563]
The ambiguity threshold button is displayed even for the default which is AVERAGE. This is confusing to the user.
Also the tooltip displayed when you hover over 'Ambiguity Threshold" is wrong. It's the same definition as 'genetic threshold'. (see image below)

The ambiguity threshold should be visible only if HIV-TRACE-g is selected as the method to deal with ambigs. Only then does the user decide what value to set. the algorithm uses this user set threshold to decide which sequences to resolve and which ones to average (see definition below):

HIV-Trace-g (Any sequence with no more than the selected proportion [0 - 1] will have its ambiguities resolved [if possible], and ambiguities in sequences with higher fractions of them will be averaged. This mitigates spurious linkages due to highly ambiguous sequences.)

![DistanceMetricOptions_AmbigThreshold.JPG](https://images.zenhubusercontent.com/60873227d0d25c1fe3daadb1/6f5c899d-9109-42fe-9489-e484766ef329)

**Comment by reagank** [comment]
Updated so that the ambiguity threshold only appears for HIVTRACE-G and RESOLVE (the only two that use that value), added to pending bugfix PR
