### ISSUE TITLE
Import HIV Trace JSON files

### ISSUE THREAD

**Issue by reagank** [CDCgov/MicrobeTRACE#565]
HIVTrace produces a JSON file that describes the network that it constructed. There is an object laying out all of the edges, an object laying out each of the nodes, and a third object laying out all of the singleton (i.e., unconnected) nodes.

**Comment by ikb6** [comment]
need to discuss JSOn import in general. Angular is assigning different thresholds than MT DEV at launch. As a result , the loaded network looks different between them both. MT DEV sets a threshold of 7 SNPs, while Angular has the deafult setting as the default for TN93 which is 0.015. As a result it has far fewer links. Once I increase the threshold to 7, the networks match (at least at first glance). But the whole point of JSON input is that the user need to play with threshold settings. Lets discuss at the meeting on 7/27

**Comment by ikb6** [comment]
Tested and it works. There is a tiny difference in the number of nodes between the network built using the HIVTrace JSON (189 nodes, 201 links) and that using FASTA (188 nodes, 199 links). NOt sure why this is and how crucial

**Comment by ikb6** [comment]
WIll check to find discrepant node
