### ISSUE TITLE
ANGULAR: Unable to load distance edgelist and node list combo

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#581]
I tried to load a distance edge list along with the corresponding nodelist, and it freezes. If I load just the nodelist which has a sequence column, then it is able to draw the correct network using the seqs in that column. I'll email you the files, unable to attach here

**Comment by roxycintron** [comment]
I can load a link (edge) file and launch the network. Also, I can load node and fasta files and launch the network. However, when I load link, node and fasta files, the network fails to launch (I tested with the Epi-Gen test files available in MS Teams).
