### ISSUE TITLE
ANGULAR: Menu bar disappears after loading newick file and launching the network

### ISSUE THREAD

**Issue by roxycintron** [CDCgov/MicrobeTRACE#592]
**Describe the bug**
When I drag and drop a newick file onto the app and click 'Launch' it loads the '2D Network' but the Menu bar on top of the screen disappears.

**To Reproduce**
1. Drag and drop the newick file or click option to load the file
2. Click on 'Launch'
3. See only 'Files' and '2D Network' tabs but no Menu bar on top of the screen.

**Expected behavior**
Menu bar should be available on top of the screen to be able to load the 'Phylogenetic Tree' view (or any other view). 

**Screenshots**

![image](https://user-images.githubusercontent.com/71835013/197624632-b3cf36f3-117a-4916-a9fb-28b5d7e0b603.png)

**Desktop (please complete the following information):**
 - Browser [Chrome]

**Comment by roxycintron** [comment]
The issue was related to the zoom settings in the webpage. This is an updated view of the phylogenetic tree after loading and launching the newick file. The top menu bar is visible at 100% zoom setting. This issue has been solved.

![image](https://user-images.githubusercontent.com/71835013/199574606-217e6d8a-5712-4044-b5bf-7615a2144697.png)

**Comment by reagank** [comment]
Resolved
