### ISSUE TITLE
ANGULAR: 2D Network fails to launch after loading fasta file

### ISSUE THREAD

**Issue by roxycintron** [CDCgov/MicrobeTRACE#593]
**Describe the bug**
When I drag and drop a fasta file onto the app and click 'Launch' the '2D Network' fails to launch.

**To Reproduce**
1. Drag and drop the fasta file or click option to load the file
2. Click on 'Launch'
3. The '2D Network' fails to launch

**Expected behavior**
2D Network launches after clicking on 'Launch'

**Screenshots**
![image](https://user-images.githubusercontent.com/71835013/197628279-d78038ba-04d8-4d09-8f4e-95839cb3046f.png)

**Desktop (please complete the following information):**
 - Chrome

**Comment by roxycintron** [comment]
There is still an issue launching the network after loading FASTA file.

![image](https://user-images.githubusercontent.com/71835013/199576796-9353b557-adf0-46d6-86e9-2f628fc616b5.png)

**Comment by roxycintron** [comment]
SOLVED - I can load the fasta file and launch the 2D network. I can also select the "Phylogenetic tree" view and generate 
 the correct tree.

**Comment by reagank** [comment]
Resolved
