### ISSUE TITLE
ANGULAR: Need a Global Settings Menu in the main menu

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#595]
Right now, you cannot change distance thresholds or do any Global settings unless you go to Node settings, open the color menu which then launches it. We need to just open **Settings** as we do in the current version.

**Comment by roxycintron** [comment]
You can select _Settings_ if you go to the Window tab in the menu as shown below. I think this is ok but will need to update in the manual. Alternatively, create a separate tab for settings in the main menu (it's a separate tab in classic MT).

![image](https://user-images.githubusercontent.com/71835013/200608289-2c837977-43d2-4658-a9c4-6378bd83731e.png)
