### ISSUE TITLE
Recursive selection of tips in phylogenetic tree

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#60]
Selecting a non-terminal branch in a phylogenetic tree should automatically select all tips that are downstream from that branch. 

See arrow and highlights below:
![image](https://user-images.githubusercontent.com/1420108/47929436-60ccc900-de9f-11e8-8408-bb06e71b4688.png)

**Comment by AABoyles** [comment]
This is a great idea! Unfortunately, Phylotree doesn't give us sufficient control to make this happen (or rather, it does, but every way I've tried is broken). Punting until Phylotree v3-to-v5 enters production.
