### ISSUE TITLE
ANGULAR: Wrong statistics and minimum cluster size

### ISSUE THREAD

**Issue by roxycintron** [CDCgov/MicrobeTRACE#604]
**Describe the bug**
I loaded a fasta file and launched the 2D network. The network is loaded correctly but the statistics are wrong. Also, if you change the minimum cluster size, both the network and statistics are wrong.  The statistics are not being calculated correctly when the network is loaded and are not updating when the cluster size is changed.

**To Reproduce**
1. Load Fasta file and click Launch
2. Select the Window tab in the main menu and go to _Settings_
3. Select 'Show' Statistics
4. Change the 'Minimum Cluster Size'
5. See errors in network and statistics view

**Statistics Comparison: Angular vs MT Dev**

**Angular - Wrong Stats**
![image](https://user-images.githubusercontent.com/71835013/200624907-249fc5c9-8662-4d6a-ac10-9f15df595b99.png)

**MT Dev - Correct Stats**
![image](https://user-images.githubusercontent.com/71835013/200625044-4a28845d-c668-44a4-bbc2-15b6ecf35e2f.png)

**Minimum Cluster Size Comparison: Angular vs MT Dev**

**Angular - Wrong Cluster Size and Stats**
![image](https://user-images.githubusercontent.com/71835013/200626501-efe2a23f-c1e3-4440-86b7-7c5e9854c312.png)

**MT Dev- Correct Cluster Size and Stats**
![image](https://user-images.githubusercontent.com/71835013/200626692-760a83fd-a2f0-4bb6-b300-b207f120c4e3.png)

**Desktop (please complete the following information):**
 - PC
 - Browser [Chrome]

**Comment by mossy426-cdc** [comment]
@roxycintron This may have resolved itself after fixes have been made.  I cannot reproduce.  If you can, please send me the FASTA File you used.
