### ISSUE TITLE
ANGULAR View Settings display incorrectly when re-opened

### ISSUE THREAD

**Issue by reagank** [CDCgov/MicrobeTRACE#611]
When view settings are opened for the second time all of the accordian components are expanded and not collapsed like they should be

How to reproduce:

Open settings in 2D view
Close the settings window
Open the settings again

**Comment by mossy426-cdc** [comment]
The problem was with the library we are using for the modals (Primeng).  It is a known issue with this library, so as a workaround I have it so it manually closes the tabs on reopen unless the tab was already openned by the user when they closed the window.
