### ISSUE TITLE
Loading files

### ISSUE THREAD

**Issue by apbvreddy** [CDCgov/MicrobeTRACE#621]
The program doesn't load the three files, (1) fasta, (2) link files with source, target and dist values (3) metadata for corresponding spicies (source) ids. What could be problem? Please explain.
Thanks
Vijay

**Comment by mossy426-cdc** [comment]
Hi Vijay,

We're testing the application with different file types and don't see this issue at the moment.  

Can you check and confirm that the IDs are all the same in each file type, and no mispellings?  

If they're all the same and you're still having a problem, can you give a bit more detail about your steps to reproduce this issue you're having?

Hope to resolve this for you soon!
Evan

**Comment by ikb6** [comment]
Vijay, 
Once you try what Evan suggested, if you are still having the issue, you can attach files here if it's not sensitive data, or send it to me  ikb6@cdc.gov, and I can take a look.
Anupama
