### ISSUE TITLE
ANGULAR: unable to add  data

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#625]
I had loaded a sequence nodelist, and wanted to add an epi edgelist. Unable to add data using the File dropdown on main menu.

**Comment by mossy426-cdc** [comment]
Data can be added all together now in the local veriosn I have.   I am working on the overlay dotted lines/key box now and will deploy it to the url for testing once resolved.

**Comment by ikb6** [comment]
This works, but had some issues loading a COVID dummy dataset. ALso, color links by origin has to be the default setting when network loads
