### ISSUE TITLE
ANGULAR: error in filtering tab when I load session file

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#647]
Loaded an HIV session file (distance is in TN93). But when I open Settings menu and try to filter, the distance is displayed as SNPs even though the distance metric says TN93. Also, the mini histogram is missing. Will email you session file with Issue number in subject line.

It looks like irresepective of what session file you load, distance metric is displayed as TN93, and actual values in threshold are displayed as SNPs. See below image froma COVID session file I loaded where the distance metric was SNPs.
![Session_Distance_thresholdScreenshot.JPG](https://images.zenhubusercontent.com/60873227d0d25c1fe3daadb1/be93059e-007a-47e3-ade5-dab6ba1bc3eb)

**Comment by ikb6** [comment]
![TN93_session_distThreshold_SNPs.JPG](https://images.zenhubusercontent.com/60873227d0d25c1fe3daadb1/5afe335e-e8e9-49df-945c-50b7141c6ddb)

**Comment by ikb6** [comment]
This is still an issue. Just loaded a COVID dummy dataset. dist metric should be SNPs, and threshold increase decrease should be in integers

![ZenhubIssue647.PNG](https://images.zenhubusercontent.com/60873227d0d25c1fe3daadb1/36e4b229-705c-413f-a738-c2bf8af2aa28)

**Comment by ikb6** [comment]
Emailing you session file for this issue

**Comment by mossy426-cdc** [comment]
I have loaded the session file and the TN93 vs snps appears to work for me?  Might have fixed it in a previous resolution.  

As for filtering bars not disaplying, the issue was that is had the same implementation for rendering as javascript to update the element in html.  Angular uses a shadow dom and the way it access the filtering bars svg is a bit more complex.  I added the necessary functionality to access the filtering bars properly and the update worked properly and displays the bars.  Will push soon.

**Comment by ikb6** [comment]
STill seeing this issue. My session file is a SNP network, but when I open settings, it displays metric as TN93, and the theeshold adjustment is also in decimals vs integers

**Comment by mossy426-cdc** [comment]
Ok,  I'm seeing the session file you have doesn't have a value for the distance metric and TN93 is default for a session.  How did you create this session file through angular or dev?

**Comment by ikb6** [comment]
DEV

**Comment by mossy426-cdc** [comment]
So there was an issue where it would default to tn93 anyways even with correct info.  Reason being there are a bit of unused variables from the older code that need edto be cleaned up and one of them was for distance metric that was assiging Tn93 by default and never changed.  Another issue is that in the HTML, tn93 was selected by default even if the value was snps.  Should be resolved now.

**Comment by ikb6** [comment]
Still seeing this. Can discuss at meeting

**Comment by mossy426-cdc** [comment]
Ok I believe that there are just multiple related, but separate issues.  It should be fixed so when you load your session file it'll appear correctly.  The issue with the file you have was that there was no default-metric property in your session file, which is unrelated to Angular being able to load it properly.  I'll have to check out dev's saving to ensure it saves that variable in the session file.
