### ISSUE TITLE
ANGULAR: Downlaod table not working

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#665]
Cannot find the downloaded file, an dit does not ask me for location where I want to save the xlsx

**Comment by Dev-AniketJadhav** [comment]
I had solved this issue previously. Just wanted to know if you are using Angular data table ? Let me know if you want my help. Thank you

**Comment by mossy426-cdc** [comment]
We are using primeNG table.  We are in the middle of production for the angular application and do not need assistance with that at the moment, but appreciate the offer!

**Comment by dacowan404** [comment]
fixed bug prevented table from being exported; can now export as excel file or csv
