### ISSUE TITLE
Sequence View Zoomer

### ISSUE THREAD

**Issue by AABoyles** [CDCgov/MicrobeTrace#67]
We'd like to be able to zoom into and out of the sequence viewer, similar to how zooming in the Network and Map views work. The sequence viewer is a canvas, and we don't need to recompute it on every zoom (it'd take too long). Instead, we can basically copy the `zoom` function from [this example](https://bl.ocks.org/mbostock/3680958).

**Comment by JulJen** [comment]
I'll take this issue.
