### ISSUE TITLE
Duplicate Nodes when Uploading Node List, Distance Link List, and Epi Link List

### ISSUE THREAD

**Issue by qqh3-cdc** [CDCgov/MicrobeTRACE#688]
Repro Steps
1. Open 2 MicrobeTrace sessions in Edge (use InPrivate for the 2nd)
2. Upload the files attached
![image.png](https://images.zenhubusercontent.com/649cc14090d9753a7231ea3b/b9f8727b-0c72-41ef-bca7-1956cac3ddb1)
3.  See graph stats. There are 4 singletons vs 5 singletons. Now, hover over the singletons. 30576_KF773440_B96cl58 is a duplicate.
![image.png](https://images.zenhubusercontent.com/649cc14090d9753a7231ea3b/df79c71a-162e-4008-907e-7ed860486f24)
![image.png](https://images.zenhubusercontent.com/649cc14090d9753a7231ea3b/97994a5f-da58-463c-9838-ad1677609452)
[https://app.zenhub.com/files/149786212/993d8289-7aba-420d-b400-4e97fbddcf92/download](https://app.zenhub.com/files/149786212/993d8289-7aba-420d-b400-4e97fbddcf92/download)
NOTE: The same bug occurs when using Node List, NWK, and Epi Link List. Also Node List, Distance Matrix, and Epi Link List. (30576_KF773440_B96cl58 is duplicate). For both cases, with or without epi link list produces same bug. Hopefully it's not a test data issue.
[https://app.zenhub.com/files/149786212/8ace74ef-a93b-4ab1-9659-2f2b69077ea4/download](https://app.zenhub.com/files/149786212/8ace74ef-a93b-4ab1-9659-2f2b69077ea4/download)

**Comment by mossy426-cdc** [comment]
I've been trying to reproduce and cant.  I think it could be that there might be a white space somewhere on that node within the datasets you're using.  We'll chat on the call
