### ISSUE TITLE
After saving and loading a session, customized colors of nodes change

### ISSUE THREAD

**Issue by qqh3-cdc** [CDCgov/MicrobeTRACE#693]
1. Upload node list with seq
2. Color by node index and make the colors unique (use lighter and darker shades)
![image.png](https://images.zenhubusercontent.com/649cc14090d9753a7231ea3b/ed1572bb-e266-4712-ab83-13a11460f90c)
3. Save the session, reload MicrobeTrace and load session
4. The customized colors have changed (see 30582_KF773578_H96cl11)
![image.png](https://images.zenhubusercontent.com/649cc14090d9753a7231ea3b/625059ed-9dfb-4063-a3df-3c89231faa98)

**Comment by mossy426-cdc** [comment]
This appears to have been inadvertantly fixed.  I cannot reproduce.  @ikb6 can you confirm?

**Comment by billswitzer2** [comment]
It happened to me today.

**Comment by mossy426-cdc** [comment]
You've been testing the angular URL?
________________________________

**Comment by mossy426-cdc** [comment]
I'm going to need a dataset or something to reproduce this as I used the same dataset mentioned by Andrew and I cannot reproduce it.
________________________________

**Comment by billswitzer2** [comment]
Not working in dev…

**Comment by ikb6** [comment]
I am not able to reproduce this bug. Bill if it happened to you today, could you share the dataset with Evan?

**Comment by billswitzer2** [comment]
Sorry, my issue is different. The colors in my style file are not working properly but could be from some node IDs changing.

**Comment by mossy426-cdc** [comment]
Got it, yes I believe changing the node ids will alter it.
________________________________

**Comment by billswitzer2** [comment]
Glad you’re feeling better…

**Comment by mossy426-cdc** [comment]
Yes much better, thanks!
________________________________
