### ISSUE TITLE
Size Slider Does Not Change Size

### ISSUE THREAD

**Issue by qqh3-cdc** [CDCgov/MicrobeTRACE#698]
For any file combination, select size by degree. Change the size slider. The nodes don't change size.
![image.png](https://images.zenhubusercontent.com/649cc14090d9753a7231ea3b/62ce9c50-31ac-4c3a-8069-211187fb71ba)
![image.png](https://images.zenhubusercontent.com/649cc14090d9753a7231ea3b/6bf4aa1f-9937-4163-96d9-4b2eb931d00a)

**Comment by mossy426-cdc** [comment]
The fix for 687 resolves this.
