### ISSUE TITLE
Session and Gridlines Don't Extend When Making Window Larger

### ISSUE THREAD

**Issue by qqh3-cdc** [CDCgov/MicrobeTRACE#699]
Make window half screen. Load any dataset. Select 2D Network Settings > Display > Gridlines > Show.
![image.png](https://images.zenhubusercontent.com/649cc14090d9753a7231ea3b/156f7c12-dae7-4558-ae56-9391e80a1c3b)
Now, make the window full screen. You cannot drag any nodes to the other side of the screen. Also, the gridlines only extend half screen.
![image.png](https://images.zenhubusercontent.com/649cc14090d9753a7231ea3b/9012d137-8d5c-4995-8541-68d77a3a183c)
![image.png](https://images.zenhubusercontent.com/649cc14090d9753a7231ea3b/fb950e21-681b-490d-8eff-e15bc53a94ac)

**Comment by mossy426-cdc** [comment]
Issue is that the gridlines should be rerendering as the visualization rerenders.  Fix will be pushed soon.

**Comment by mossy426-cdc** [comment]
Turned out to be more than that.  Needed to add extra functionality for not only adding new lines as the window gets larger, but also updating their length.
