### ISSUE TITLE
"Hide Cluster" function possibly not working

### ISSUE THREAD

**Issue by vto6-cdc** [CDCgov/MicrobeTrace#70]
Hey Tony,

I'm working on the 2D network diagram and am trying to select the "Hide Cluster" option when I right-click on a particular node. However, I'm not sure it is working as intended, as it does not hide from the 2D network and when I click on "Attributes", the visibility still = 'true'. I may be using it improperly but wanted to run it by you.

SC

**Comment by AABoyles** [comment]
Hey Scott,

We've had a bunch of difficulty working with that "Hide Cluster" functionality. You're using it properly, it's just not responding properly. We've talked about removing the feature entirely, but it sounds like you might need it?

Tony

**Comment by vto6-cdc** [comment]
Hi Tony,

No worries! I actually was playing around with it when I realized I could just use the “hide all singletons” function so it ended up working out ok for me.

You can remove the feature and it wouldn’t hurt my feelings. ☺

Scott
