### ISSUE TITLE
Polygon Grouping and Color Chart Don't Update

### ISSUE THREAD

**Issue by qqh3-cdc** [CDCgov/MicrobeTRACE#700]
Upload any file type combination [https://app.zenhub.com/files/149786212/d19ee04b-1865-4ff8-aa4c-9177f47e0151/download](https://app.zenhub.com/files/149786212/d19ee04b-1865-4ff8-aa4c-9177f47e0151/download). 
Use the following settings...
2D Network Settings > Polygons 
    > Polygon Controls > Show
                                    > Center [Should this be a different name??] > Cluster
    > Labels > Label Polygons > Show
                   > Orientation [Should this be a different name??] > Cluster
    > Colors > Color Polygons > Show
                   > Polygon Color Table > Show
Global Settings > Filtering Threshold > 0.001
![image.png](https://images.zenhubusercontent.com/649cc14090d9753a7231ea3b/3252bc35-31e6-4ba5-8a50-3a65ee940443)
Change Global Settings > Filtering Threshold > 0.0001
![image.png](https://images.zenhubusercontent.com/649cc14090d9753a7231ea3b/dde52a51-6ba2-4c10-8767-c173118e3bff)
The Link Color Table correctly updates. Polygon Color Selection Table does not. When Colors > Color Polygons in toggled on and off, it correctly updates.
![image.png](https://images.zenhubusercontent.com/649cc14090d9753a7231ea3b/ab54caae-5bca-4398-b226-3bc47639e2a3)
Also note, the cluster of 2 does not have a respective polygon.

**Comment by ikb6** [comment]
This is seen in DEV as well.

**Comment by mossy426-cdc** [comment]
Issue was there it was only in the user interface.  There was no functionality for this in the code other than disaplying it.  I have implemented the functionality for it and will push the fix soon.
