### ISSUE TITLE
Node and Link Color Tables Disappear When Exporting 

### ISSUE THREAD

**Issue by qqh3-cdc** [CDCgov/MicrobeTRACE#701]
Upload files
Color code nodes and links
Try and export
The node and link color tables disappear
![image.png](https://images.zenhubusercontent.com/649cc14090d9753a7231ea3b/9a1272df-f287-48f0-a2b2-1aff6ff54a66)
![test.png](https://images.zenhubusercontent.com/649cc14090d9753a7231ea3b/da974649-1bad-4ce0-8f64-e7f262ecfdd4)

**Comment by mossy426-cdc** [comment]
Closing as this is referenced in issue #653
