### ISSUE TITLE
Exporting as SVG Cuts Off 2D Network

### ISSUE THREAD

**Issue by qqh3-cdc** [CDCgov/MicrobeTRACE#703]
![image.png](https://images.zenhubusercontent.com/649cc14090d9753a7231ea3b/89c7677c-ea3a-4d54-8cc9-0712fdb75da8)

SVG does not appear in Zenhub
![test2 (2).svg](https://images.zenhubusercontent.com/649cc14090d9753a7231ea3b/7fbdcbad-2ebb-44b1-8094-7d2fbba96f39)

**Comment by mossy426-cdc** [comment]
Closing as this has been reported in #653
