### ISSUE TITLE
Add "Update" Functionality

### ISSUE THREAD

**Issue by mossy426-cdc** [CDCgov/MicrobeTRACE#705]
I have the functionality ready to push, but waiting till other bugs are fixed before adding this as it can have the potential to cause issues (it affects the entire sesion data) in another area and it'd be best to determine that this was the cause after fixing the other bugs first.

**Comment by ikb6** [comment]
Is this pushed? Can I test?

**Comment by mossy426-cdc** [comment]
Yes!
________________________________

**Comment by mossy426-cdc** [comment]
For dev
________________________________

**Comment by mossy426-cdc** [comment]
Just deployed to angular.  Should be available in 15.
