### ISSUE TITLE
MTDEV: But still high priority Session file is not saving distance metric values

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#706]
Following up on discussion at MT DEV meeting...When I save a SNP network session in MT DEV, and then open it in Angular (or MT DEV), it opens using the default distance metric setting, which is TN93. MTDEV  should save distance metric info while saving a session, so that when it is opened, the session retains that same saved value (SNP or TN93)

**Comment by mossy426-cdc** [comment]
There were duplicate keys for default-distance-metric within the session file that seemed to impact the value.  I saved a SNPs session after removing it and loaded it correctly into angular.  Let me know if this resolved the issue.

**Comment by ikb6** [comment]
When I try to adjust distnace threshold on the session file after saving and re-loading, it still shows decimals
