### ISSUE TITLE
Legend does not refresh upon filtering links

### ISSUE THREAD

**Issue by vto6-cdc** [CDCgov/MicrobeTrace#71]
Hi Tony,

Another issue to bring to your attention. Essentially what is happening is when using the 2D network diagram, the legend will not refresh to reflect additional clusters should I decrease the filtering threshold of the links from 0.015 genetic distance to 0.005 genetic distance. I am using a fasta file and the default of MT is at 0.015 for visualization. I "hide" singletons, and then I edit the legend to give each Cluster ID a different name (i.e. Cluster '8' becomes Cluster 'A', since colleagues have given it that name). There are fewer clusters ('larger') using the 0.015 threshold. Using the filter threshold option to 0.005 this breaks out the clusters ('smaller'), but the legend does not update (i.e. there were 6 clusters, but restricting the genetic distance breaks it out to 8). Just wanted to bring this to your attention. 

SC

**Comment by AABoyles** [comment]
Good bug! I'll look into it. Thanks, Scott!

**Comment by AABoyles** [comment]
Hey @CopeSc,

I've taken a stab at fixing this. Would you mind testing it for me to see if it does what you expect? [Try it out here](https://devmicrobetrace.herokuapp.com/).

Thanks,
Tony

**Comment by AABoyles** [comment]
I believe this is resolved. Will reopen if not.
