### ISSUE TITLE
MT DEV: epi data overlay not working

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#710]
It works in PROD, so wondering if it's a GA4 issue again. Adding epi data does nothing. Will send video with console message

**Comment by mossy426-cdc** [comment]
Issue was with the newer "update" functionality, were I reset the session on update to account for file that are deleted and recalculate everything.  However that seems to break adding data.  Looking into it, but reverted changes for now so that this works.
