### ISSUE TITLE
ANGULAR- SNP dataset distance labels need to be integers

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#718]
When I load a SNP dataset, distance label should be an integer. It right now shows as 16.000 or 3.000

**Comment by mossy426-cdc** [comment]
Pushed, should be avialbe in a couple minute.  Putting on distance labels didnt check for snps vs integers.  I added the condition and it works.

**Comment by ikb6** [comment]
This is resolved, but residual minor issue possibly related. When I use up doen arrows toadjust SNP threshold in the Settings menu, it shows as decimal, and does not go up and down as integers. See screenshot

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGZ2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--de519f35e1fcb41c22c1eec2baa22ca0fd66934e/SNP%20thresholds_settingsMenu.PNG)

**Comment by mossy426-cdc** [comment]
Please test if this is resolved soon.  Making a push.  I have it so that when changing the values in the buttons it shows as integer v decimal depending on metric. I see it reflected in the filtering threshold value of global settings as well as in the labels.  Int for snps and dec for tn93.

**Comment by ikb6** [comment]
Yes, resolved!

**Comment by billswitzer2** [comment]
Great!
