### ISSUE TITLE
ANGULAR: sort by node count is not working in key table

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#719]
When you color nodes by an attribute, the sort function by node count  is not working

**Comment by mossy426-cdc** [comment]
Hey anu, can you double check you were pressig the right sort?  I can't reproduce, but I did get confused for a bit but it seems I was pressing the wrong sort because of the positioning.  What I thought was the sort for count was actually the sort for Name and count was the next sort icon.
