### ISSUE TITLE
ANGULAR and DEV- Rename polygon settings 'Cluster'

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#721]
In the Polygons controls, we discussed renaming "Center" to "Group By". See pic

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVNsIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--16d3f56ef2341e183b5ebfa996432eb54dcbbdc0/PolygonControlsRename.PNG)

**Comment by mossy426-cdc** [comment]
Pushed to both.  Angular updates should be visibl in a coupe minutes.
