### ISSUE TITLE
ANGULAR: Drop down for Polygon label orientation is wrong

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#723]
Drop down menu for Polygon label orientation should have left right, top bottom etc. Instead it has attributes from nodelist

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBay92IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e788684da93f5627027d1db7c7940fcc33d2de85/Polygon%20LabelOrientationDropDown.PNG)

**Comment by mossy426-cdc** [comment]
This was missing implementation.  Added it and pushed.
