### ISSUE TITLE
ANGULAR: Link tooltips do not work

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#725]
I don't see anything if I hover over link. This is only in Angular. Works in PROD

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbS92IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4b550cd519fe81abf638ebece5489572419c8993/LinkTooltip.PNG)

**Comment by mossy426-cdc** [comment]
Figured out the reason is because the brush element is toggled on for multiselect which doesnt allow for labels to be show on hover.  I made the default be toggled off since we don't want to have multiselect functionality started when the session loads.  Now lables should show.
