### ISSUE TITLE
Problems with site (site https://microbetrace.cdc.gov/)

### ISSUE THREAD

**Issue by ffvasilev** [CDCgov/MicrobeTRACE#731]
Hello, since October 10, 2023, I have been unable to open the page " https://microbetrace.cdc.gov/".
I tried it on different PCs and used different browsers.

**Comment by ikb6** [comment]
@ffvasilev , our developer is looking into it- meanwhile, please use our dev version

https://cdcgov.github.io/MicrobeTrace/

**Comment by billswitzer2** [comment]
The prod version of MicrobeTrace is back up. Thanks for alerting us to this issue and also for your patience.
Bill
