### ISSUE TITLE
MTDEV-MAP View: Tabs of individual views are not seen at 100%

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#734]
Seeing this phenomenon only now after these map tiles were pushed. Not seeing it in PROD.
When MT DEV loads, you cannot see the tab of each individual view (File, Map view etc) at the regular (100%) browser setting. When I drop it to 90% it becomes visible. Not sure why new map tile source should do it. Will need someone else to reproduce in case it is my screen. (Should not be because PROD works fine)

MTDEV at 100%
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGxNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a663a7d538727ca3cc082d2c391a3cd0c22206f8/image.png)

MTPROD at 100%

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGhNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49e0e00379ebf1730fa7764fb77f38fe4a312908/image.png)

**Comment by mossy426-cdc** [comment]
The reason for this issue is because the text non-production text has been updated and is much longer, so it goes down to the next line when the screen width is not wide enough – covering the tabs as the top. Working on a workaround.

**Comment by mossy426-cdc** [comment]
Just sent a push making it so the margin between the nav tabs and non-productiont abs have been reduced.  Let me know if that works for you. Should see the updates in about 15.
