### ISSUE TITLE
Angular: No loading animation (rotating DNA helix); mini histogram issues

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#748]
The DNA helix animation while loading files is gone.
Also when you hover over the bars of the mini histogram in Filtering tab of Settings, no calues are seen. Bill also saw NA when he hovered over the bars. See video and JPEG here

https://cdc.sharepoint.com/:f:/r/teams/nchhstp-dhap-lb-microbetrace/Shared%20Documents/General/Files%20for%20bug%20reports?csf=1&web=1&e=ZdHbJG

**Comment by mossy426-cdc** [comment]
As for loading animation, it was commented out previously.  I commented it back in and the route to the animation was broken.  Accessing the route through the common service fixed the problem.

**Comment by billswitzer2** [comment]
Thanks!

**Comment by mossy426-cdc** [comment]
As for the values not being seen, that hadn't been implemented in angular.  I've gone ahead and added it.  Will push thesee updates soon.

**Comment by billswitzer2** [comment]
Thanks! Assume you mean the values in the distance histogram.

**Comment by mossy426-cdc** [comment]
Yes, you should see the changes now.

**Comment by billswitzer2** [comment]
ty
