### ISSUE TITLE
ANGULAR- Searching for ID does not highlight node (2D view) or row (in Table view)

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#755]
Searching for an ID in table view should highlight the row in orange and also float it to the top of the table. It should also highlight the node in 2D view. This is not happening.

**Comment by mossy426-cdc** [comment]
Searching for node works for me in 2d network.  Can you restest?

**Comment by ikb6** [comment]
Yes, I re-tested;  it now highlights the node in 2D view. But not in Table view

**Comment by ikb6** [comment]
Search is working in Table View, but it does not float it to the top. Also unable to test by searching for nodes in other pages, because Table view displaying only 1 page of entries see related new issue
