### ISSUE TITLE
Hide tables when on Files view

### ISSUE THREAD

**Issue by mossy426-cdc** [CDCgov/MicrobeTRACE#758]
When navigating to the files tab, all the tables are still visible.  They should be hidden when the files view is open and appear when navigating back to another view.

**Comment by mossy426-cdc** [comment]
I'm about to make a push.  

Added a handler for checking when the golden layout is changed in the golden layout service.  Depending on the tab title of the new tab (i.e "Files") I'll hide/show the tables.

**Comment by ikb6** [comment]
This is still not fixed
<img width="1214" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXExQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1df1757c18855529f0b94a89240b07f02bce018c/image.png" alt="image.png" />
