### ISSUE TITLE
ANGULAR: Phylogeny. Seeing negative branches

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#765]
Please see input file I used- It's a NWK tree, can be found at this link

https://cdc.sharepoint.com/:f:/r/teams/nchhstp-dhap-lb-microbetrace/Shared%20Documents/General/Files%20for%20bug%20reports?csf=1&web=1&e=0SGxGE

<img width="1445" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDJYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--895884aee8d9410679c9b3b9927d808a47c3dad8/image.png" alt="image.png" />

**Comment by reagank** [comment]
I'm not seeing a negative branch length for cdcgov or mossy426 - this is what I'm seeing (with distance labels enabled)
<img width="1879" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0NZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83c8a7074c17db3db36e560f6ef9993ef9419fe9/angular_newick_tree.jpg" alt="angular_newick_tree.jpg" />

**Comment by ikb6** [comment]
I am talking about the two branches that extend to the left of the root. That is not correct. And even the rest of branches look different from how they look if I open this nwk file in a different tree viewer like MEGA (I sent a detailed email about that)
