### ISSUE TITLE
ANGULAR- need to change buttons on other views

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#768]
Need to replace buttons on other views with the new clearer 3D style buttons which you have added to 2D network

<img width="568" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU8xQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df92ea51d70f1c6e33f04091578f4309e39dd556/image.png" alt="image.png" />

**Comment by mossy426-cdc** [comment]
Added button styles to other views.
