### ISSUE TITLE
Angular: Map view. Link transparency slider not working

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#769]
In the map view, link tab, transparency slider does not work.

<img width="1281" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXkxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8e4388798d375994cb77ceea20f9ceb3c797a92/image.png" alt="image.png" />

**Comment by mossy426-cdc** [comment]
I am able to change transparency. Could be fixed with the ovverlay functionality I updated it with.  Please test once changes are in.
