### ISSUE TITLE
ANGULAR: Map view- Components tab - link needs to be made active

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#770]
The Read More link is inactive

<img width="688" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3kxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f306c8dd0c8eb09bcc8adde725475de4b4797d0d/image.png" alt="image.png" />

**Comment by mossy426-cdc** [comment]
There was no link value.  Added the link from dev and set target to blank to open to a new tab.
