### ISSUE TITLE
Angular- Table view- Link tab and cluster tab does not seem to work

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#776]
When I click on link tab, I see the same thing as Nodes tab

<img width="1249" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMExnQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe481b739b0a6c2b0aa5e6249d7ef6cfdb3e949e/image.png" alt="image.png" />

**Comment by mossy426-cdc** [comment]
Issue was that the way the values were being accessed in the html from the typescript.  Have fixed it to access the correct values and just made a push.  Should be visible soon.
