### ISSUE TITLE
Angular: Table View showing only 1 page of entries

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#780]
Table view displaying only 1 page of entries (nodes 1-9)

<img width="1565" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHRJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--76997d4f9fe529c522df810348fdf9b9ded9e041/image.png" alt="image.png" />

**Comment by dacowan404** [comment]
pagination element with buttons to change the page and the number of rows per page is now centered on the screen
