### ISSUE TITLE
Angular: Node/Link color tables appear/disappear in different views

### ISSUE THREAD

**Issue by roxycintron** [CDCgov/MicrobeTRACE#788]
**When a new view is selected, the node color table appears in the new view. If you go back to the 2D network view, the link color table disappears. If you close the node color table and open a new view, it appears again in the opened views.**

**To Reproduce**
1. Select "Continue with Sample Dataset" in the Angular launch page. The network renders correctly. Note the node and link color tables.
![image](https://github.com/CDCgov/MicrobeTrace/assets/71835013/e4b92589-0839-420c-9e8b-1f316e3c18a8)

2. Select 'Table' (or any of the other views) and see the node color table.
![image](https://github.com/CDCgov/MicrobeTrace/assets/71835013/9ebe2164-aa6d-4c70-b8a2-62f0e270e2c6)

3. Go back to the 2D network view and see that the link color table is missing.
![image](https://github.com/CDCgov/MicrobeTrace/assets/71835013/ec8df9df-5e1c-4e3d-99f1-937eb0e9298f)

4. Close the node color table in any of the views and select another view tab or open a new view. The node color table appears again.

5. Go to 'Settings' and select to show link color table but it will not show up.
![image](https://github.com/CDCgov/MicrobeTrace/assets/71835013/020c7f7c-f243-40c8-ac68-b2fb0d37b30a)

**Expected behavior**

- The link color table should appear in the 2D network after changing views unless the user closes it.
-  If user closes a color table, it shouldn't appear in any of the views unless the user selects to show the color table again. 
- Color tables are more useful for 2D network, map and phylogenetic tree views. It's ok if they show up automatically in those views. If user closes them, they shouldn't reappear. 
- Can we code for color tables to do not appear in table and alignment views?

**Comment by dacowan404** [comment]
Fixed bug that caused link table to not reappear in some situations. Also node color table and link color table automatically show and hide based on view selected and value of color node/links by.
Currently, if a user hides a table in 2D Network then clicks another view where the table is presents (such as going from 2D -> map, going from 2D -> table -> 2D) then the table reappears. May want to change this in the future.
