### ISSUE TITLE
ANGULAR: Need ability to save as a style file

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#789]
Angular does not give the option of saving a style file unlike PROD. It is an important feature for people who use MT for different datasets but need the same color scheme/styling schema.

<img width="1009" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG5tQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ff5645b1975e3d9419020a5cd6dd65e2c1bf66c/image.png" alt="image.png" />

**Comment by dacowan404** [comment]
I have fixed the issue with exporting style file. While fixing this problem, I found that importing style file wasn't working either. Currently fixing importing of style file. I will deploy to mossy url once I have fixed both issues.

**Comment by dacowan404** [comment]
Style files can now be imported, and settings will be applied. I tested on global settings, file, 2d network, alignment, and map. Might need additional work for table, epi, and tree views
