### ISSUE TITLE
Angular: Message pops up on load screen

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#790]
When I add files, I see this message 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHdEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--694f9a36f6b9f343a802868640b5e7a5be037083/PleaeAddData_Bug.JPG" alt="PleaeAddData_Bug.JPG" />

**Comment by mossy426-cdc** [comment]
Should be resolved in mossy.  Let me know if this still appears
