### ISSUE TITLE
Angular: key table fromPre-loaded sample dataset remains when Auspice URL is loaded

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#805]
Please see email for details
the key table from the pre-loaded dataset is staying on as an artifact when I load a Nextstrain dataset via Auspice URL.
Please see Powerpoint with details and a video attached to my email

**Comment by dacowan404** [comment]
This isn't an issue specifically related to the the Auspice URL; it's more of an issue related to the table showing up when it shouldn't and similar to issues #788. When new data is loaded, color nodes by gets set to 'None' . The table shouldn't appear unless both color node by doesn't equal 'None' and show node table equals true.

**Comment by dacowan404** [comment]
Both node color table and link color table appear/disappear based on the current view and if color node/link by equals None. Also table contents are emptied anytime if color by is set to None.
