### ISSUE TITLE
ANGULAR: Set Width of link by distance does not work until slider bar is adjusted

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#808]
I tried this feature with multiple files and it does not work immediately. I  Set Link Width By and chose distance . You do not see the width change. Then, when you drag the Max/Min slider, then you see the width is now proportional to distance.

**Comment by dacowan404** [comment]
On loading the 2D network, the variables containing the max and min link distances were set to strings instead of numbers. Fixed the bug and it is currently deployed on mossy.
