### ISSUE TITLE
Hep A FL DOH support issue: Problem CSV- not loading

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#810]
As I mentioned, Tim Doyle (Florida DOH) finally sent his data. He has exported a subset of genetic links from his overall dataset, and has a very simple file with Source, Target, distance info. I tried both PROD and Angular, the file just won't load. Stuck with this processing message below. Not sure why it's parsing extra nodes. See highlighted .

Please could you treat this as high priority? He has been very patient, but this is frustrating for him. He's hoping to publish, but stuck on this piece.

I will email you guys the problem file.

Thanks!

<img width="680" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHplQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3da8e29a2ce7b47d663151b1e97ff9b97cbbc141/image.png" alt="image.png" />

**Comment by dacowan404** [comment]
Quick Fix on production was to first convert the file to an excel file and then either set distances dropdown field in MT to 'None' or delete/rename the origin column in the excel file.
Fix deployed to mossy. Other scenarios where uploading a csv (exported from table view) and the data has both epi and genetic links (dashed/multi links) has not been fixed. To me, this scenario seems uncommon and the fix would take more time than it is worth at the moment.
