### ISSUE TITLE
ANGULAR: Issues loading a session file created in PROD

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#812]
When I load a session file created in PROD into Angular, it does not display any of the color customizations- node colors, link colors or polygon colors. File can be found here. This happened with two different session files

https://cdc.sharepoint.com/:u:/r/teams/nchhstp-dhap-lb-microbetrace/Shared%20Documents/General/Files%20for%20bug%20reports/Issue_812_HCV_WI_Jie_Anupama.microbetrace?csf=1&web=1&e=6hNyqJ

https://cdc.sharepoint.com/:u:/r/teams/nchhstp-dhap-lb-microbetrace/Shared%20Documents/General/Files%20for%20bug%20reports/Issue812_HCV2016-2017050824.microbetrace?csf=1&web=1&e=YlYkrc

**Comment by dacowan404** [comment]
Fix deployed to Mossy

**Comment by billswitzer2** [comment]
Thanks!
