### ISSUE TITLE
CrossTab View

### ISSUE THREAD

**Issue by dacowan404** [CDCgov/MicrobeTRACE#824]
Cross Tab has been added to Angular MicrobeTrace. It is currently deployed on Mossy site. It allows users to change dataset (nodes, links, clusters), change the X and Y variables, pivot the table, show raw count or proportion of total, change text size, export as csv or excel, and import settings from a style file. Let me know what you think and if you see any bugs or anything that needs to be changed.

**Comment by billswitzer2** [comment]
Thanks David!

From: David Cowan ***@***.***>
Sent: Monday, June 17, 2024 1:57 PM
To: CDCgov/MicrobeTrace ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CDCgov/MicrobeTrace] CrossTab View (Issue #824)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.
________________________________


Cross Tab has been added to Angular MicrobeTrace. It is currently deployed on Mossy site. It allows users to change dataset (nodes, links, clusters), change the X and Y variables, pivot the table, show raw count or proportion of total, change text size, export as csv or excel, and import settings from a style file. Let me know what you think and if you see any bugs or anything that needs to be changed.
