### ISSUE TITLE
ANGULAR: Polygon works only after Show color and Show label turned on

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#827]
When I turn on Show Polygon, default polygons (cluster) are displayed, but when you select a variable from drop down, no change is seen until you select both show label and show color. See video below with console open.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGZqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--346bf755cc703dea0384ca9a243898823828f13b/PolygonBug_VideoForIssue827.mp4)

**Comment by mossy426-cdc** [comment]
Fixed in local.  Pushing to mossy soon.  There was a condition for checking when show colors is try and only rerendering then.
