### ISSUE TITLE
Implement Aggregation View in Angular

### ISSUE THREAD

**Issue by dacowan404** [CDCgov/MicrobeTRACE#828]
Aggregation View has now been added to Angular on mossy url. It allows multiple table to made each aggregating the data on a selected variable, and allows users to export the data as csv.zip, excel file, json, or pdf.

**Comment by billswitzer2** [comment]
Great! Thanks, David. Anu, let’s thoroughly check this view. Thanks!

From: David Cowan ***@***.***>
Sent: Friday, July 26, 2024 1:31 PM
To: CDCgov/MicrobeTrace ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CDCgov/MicrobeTrace] Implement Aggregation View in Angular (Issue #828)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.
________________________________


Aggregation View has now been added to Angular on mossy url. It allows multiple table to made each aggregating the data on a selected variable, and allows users to export the data as csv.zip, excel file, json, or pdf.
