### ISSUE TITLE
Mossy: Key table still appears in views like Gantt

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#832]
When I first open Gantt, key table from 2D network view is not displayed, but if I shift to another tab, and come back to Gantt, the key table appears. We have seen this issue before.

<img width="1288" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEtVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e3a663123f89200571d6b6c13a8edbcbdfe2daa/image.png" alt="image.png" />

**Comment by reagank** [comment]
Node and link key tables are no longer displayed when the gantt chart is re-opened. The phylogenetic tree does show the node key table, but the tree nodes are colored according to that chart, so it's appropriate to have it there, I think.
