### ISSUE TITLE
Mossy: Gantt extra label at origin 

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#833]
Could we remove this label at the origin of the graph (highlighted in image)?

<img width="1180" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXVVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aac1c47953b5a5bb990309d0b8cf8d0cb3989413/image.png" alt="image.png" />

**Comment by reagank** [comment]
This is actually the very first date in the dateset, but the format is off and so if being displayed wrong. It should display like the other dates now.

**Comment by ikb6** [comment]
The prod version does not put the first date at the origin, but could leave it this way
