### ISSUE TITLE
Mossy: Gantt chart download and center to screen icons are not functional

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#834]
Download button does not work. Also, when you zoom in, the whole screen zooms, unlike the 2D view where the buttons stay static, and you can click the center button to fit to screen again.

<img width="1323" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3FVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2728fa630d69dedaac8c0f6a5e4fab62bff5ecdb/image.png" alt="image.png" />

**Comment by reagank** [comment]
Export in PNG, JPG, and SVG work, removed icon for centering since the view doesn't zoom
