### ISSUE TITLE
Mossy: Aggregate view edit table headings

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#837]
Can delete the "Grouped by" and "Table of node"

<img width="1367" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMCtWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0e7ad473c9fdc7bfd6db990d1272fc567a3c658/image.png" alt="image.png" />

**Comment by dacowan404** [comment]
Updated table heading in Aggregate View. Change deployed to mossy.
