### ISSUE TITLE
Mossy: Polygon label has a white background

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#851]
Pl. remove white background if possible- it is visible only on SubtypeC for some reason...

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVBmQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e93b5d5693cede7acbaf84125cb47f8db77138e/PolygonLabelsWhitebackground.JPG" alt="PolygonLabelsWhitebackground.JPG" />

**Comment by mossy426-cdc** [comment]
Went into css proprties and updated polygon labels to have transparent backgrounds.  Pushing to mossy shortly.
