### ISSUE TITLE
Mossy: Timeline makes network go wonky

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#855]
When I play Timeline, the 2D network moves to the top left corner, partly off screen. See video below

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0RnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d43945003982207039f2dd458de390e5cebd16b/BugreportIssue855.mp4)

**Comment by mossy426-cdc** [comment]
This is fixed. It autofits when the timeline starts, but when there are no nodes to disaply in the very beginning, it doesnt know where to fit so that explains why it goes off somehwere.  Pushing to mossy and will let you know when ready for testing
