### ISSUE TITLE
MOSSY: Nearest neighbor causes links to disappear

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#858]
Image 1 - regular setting, NN is not turned on

<img width="1700" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOS9nQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b57cca6cd3826c41048835b755fd1c6ff9bb9203/image.png" alt="image.png" />

Image 2- NN turned on

<img width="1480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0RnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03ee0abe1ff823c9f328e0a25672f6626f00dea4/image.png" alt="image.png" />

**Comment by ikb6** [comment]
This is still not resolved. See console notes below

link variable:  ['Genetic Distance']
main.js:8651 tn93
main.js:7131 updated compute: true
ee4a0907-978a-4a1d-9237-b8dad044f412:2366 MST Compute time:  4 ms
main.js:3528 setting link vis:  {index: 35, source: 'KF773430', target: 'KF773429', visible: true, cluster: 1, …}
main.js:3528 setting link vis:  {index: 35, source: 'KF773430', target: 'KF773429', visible: false, cluster: 1, …}
main.js:2475 get visible links:  []
main.js:7278 link aggregates:  {}
main.js:2475 get visible links:  []
main.js:2475 get visible links:  []
main.js:2475 get visible links:  []
main.js:18983 link vis rerender:  []
main.js:2475 get visible links:  []
main.js:2475 get visible links:  []
main.js:18983 link vis rerender:  []
main.js:2475 get visible links:  []

**Comment by ikb6** [comment]
This is not resolved as of Oct 9. emailing files to you @ evan

**Comment by mossy426-cdc** [comment]
Ok I've found the issue.  I found some old code that was a work around for making nearest neighbor work that seems to no longer be of use for recomputing the MST and is causing wrong nearest neighbor values.  After removing it, NN seems to be working as expected.  I've just deployed to mossy, so please test when you can in a bit and let me know how that goes 🙂
