### ISSUE TITLE
Mossy: Unovis - large network display goes beyond screen limit. 

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#868]
I uploaded Tim's dataset (distance edgelist plus nodelist with risk info). It took almost 20 seconds to load, and the network does not fit in the screen. The fit to screen (eye) button does not work either- IMAGE 1 below. 

This happens with Polygons as well- IMAGE 2 below

IMAGE 1
<img width="1522" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXNFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e814f973e641aeca151ac7fa99032582e6b93fef/image.png" alt="image.png" />

IMAGE 2

<img width="1535" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTRFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6dd133a69cf424f63eedfb8598b8c8e26b7d00b/image.png" alt="image.png" />

**Comment by mossy426-cdc** [comment]
Added zoom level property and increased the amount of both zoom in and out you're allowed to do.  Pushing to mossy for testing soon.
