### ISSUE TITLE
Pre-packaged example files as 'Stashes'

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#88]
It would be valuable for uninitiated users to be able to directly jump into some data visualizations, even when they don't have files available. We do provide people with example files, but this requires (1) download (2) unzip (3) file selection and then (4) fine tuning of each visualization. 

If a fully-customized visualization could be pre-cached for users, they could explore all of MicrobeTrace's functionality with minimal effort and time.

**Comment by AABoyles** [comment]
Cool! Here's how to accomplish it:
1. Create session files for each example session we want in the stash interface.
2. Add a button to the stash interface to load example data.
3. On click: fetch the example sessions from the server. stash them as though they were created on local machine.
4. Refresh stash table. Done!

**Comment by AABoyles** [comment]
Accomplished via a different route. Instead, visit https://devmicrobetrace.herokuapp.com/#demo
