### ISSUE TITLE
tooltip needs editing

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTrace#90]
When you look at the node settings tab (Nodes tab), at the tooltip for explaining  each characteristic, they are sometimes wrong. The one for Label Size is the same as the one for label. Similarly, under "shapes and Sizes, the shape by and size by descriptions are off
![image](https://user-images.githubusercontent.com/33426295/50920014-4a4c6c00-1412-11e9-8acc-66a922f47957.png)

**Comment by AABoyles** [comment]
Thanks! I'll get right on it!

**Comment by AABoyles** [comment]
Resolved by 6625225f4f34781d1456acf749fe9141dd412c45, 757e50cd36456aa343343c025d129495e8749484 and bfe842e96206717cf564fb1edbd51fb6533be5fc
